### Append Recap

En esta lección, vamos a explorar algunas herramientas nuevas que nos permiten hacer preguntas más detalladas sobre nuestros datos. Estos incluyen:

- Declaraciones Si
- Valores booleanos
- Operadores de comparación

Usaremos estas herramientas para investigar un conjunto de datos que contiene información sobre 7.197 aplicaciones móviles. 

Algunas preguntas que quizás queramos responder son:

- Cuál es la calificación promedio de aplicaciones no libre?
- Cuál es la calificación promedio de aplicaciones gratis?

### Como lo vamos a hacer?

Necesitamos encontrar una manera de separar las aplicaciones gratuitas de las aplicaciones no gratuitas o de compra;

- Coloque las calificaciones de las aplicaciones gratuitas y no gratuitas en listas separadas.
- Calcule la calificación promedio para cada lista.

Antes de aislar las aplicaciónes en listas, veremos como se hace uso de 'lista.append()' con el siguiente codigo:

In [1]:
from csv import reader

opened_file = open('AppleStore.csv')
read_file = reader(opened_file)
apps_data = list(read_file)


apps_names = []
for row in apps_data[1:]:
    name = row[2]
    apps_names.append(name)

for i in apps_names[:5]:
    print(i)

389879808
113954816
116476928
65921024
130242560


## 2 of 7 · If Statements

Para **aislar unicamente las calificaciones de las aplicaciones gratuitas**, debemos agregar un condición a nuestro código. Específicamente, queremos agregar una calificación a la ratings lista solo si el precio es igual 0.0:

En el ejemplo anterior, iteramos sobre el `apps_data[1:]`y para cada iteración, complete lo siguiente:

- Asigne la calificación como un 'float' a una variable nombrada 'rating'.
- Asigne el precio como un 'float' a una variable llamada 'price'. (El precio también viene como una cadena, por lo que tenemos que convertirlo en un 'float'.)
- Si el precio es igual '0.0', adjuntamos la calificación a la ratings lista (si el precio es '0.0', entonces significa que la aplicación debe ser gratuita). Siempre 'price' no es igual '0.0', el código 'ratings.append(rating)'' no ejecuta.

  
Aquí hay algunas cosas que notar sobre el if declaración:

- El if la declaración comienza con if, continúa con price == 0.0 y termina con :.
- Usa el == operador para comprobar si el precio es igual a 0.0. No confundas == con = (= es un operador de asignación de variables en Python; lo usamos para asignar valores a variables — no nos dice nada sobre igualdad).
- Indentar ratings.append(rating) cuatro espacios a la derecha en relación con el if declaración.

En la siguiente pantalla, te explicaremos if declaraciones y probar un if ejercicio de declaración.

### Instrucciones

Complete el código en el editor para encontrar la calificación promedio de las aplicaciones gratuitas.

Dentro del bucle for, complete lo siguiente:

- Asigne el precio de una aplicación como un flotador a una variable llamada price. El precio es el quinto elemento en cada fila (el índice comienza en 0).
  
- Si price == 0.0, agregue el valor almacenado en rating a la free_apps_ratings lista usando el list_name.append() función (note el free_apps_ratings ya está definido en el editor de código). Tenga cuidado con la sangría.
  
- Fuera del cuerpo del bucle for, calcule la calificación promedio de las aplicaciones gratuitas. Asigne el resultado a una variable nombrada avg_rating_free. Las calificaciones se almacenan en el free_apps_ratings lista.

['', 'id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic']
['1', '281656475', 'PAC-MAN Premium', '100788224', 'USD', '3.99', '21292', '26', '4', '4.5', '6.3.5', '4+', 'Games', '38', '5', '10', '1']
['2', '281796108', 'Evernote - stay organized', '158578688', 'USD', '0', '161065', '26', '4', '3.5', '8.2.2', '4+', 'Productivity', '37', '5', '23', '1']

In [2]:
from csv import reader

opened_file = open('AppleStore.csv')
read_file = reader(opened_file)
apps_data = list(read_file)

valor_gratis = 0.0
free_apps_ratings = []
for row in apps_data[1:]:
    price = float(row[4])
    if price == valor_gratis:
        rating = float(row[7]) # user_rating
        free_apps_ratings.append(rating)
    
avg_rating_free = sum(free_apps_ratings)/len(free_apps_ratings)
print(avg_rating_free)

3.3767258382642997


### Booleans

Este ejercicio lo que hace es mostrar el resultado de una comparación booleana, no está mál para recordarlo:

In [3]:
a_price = 1

print(a_price == 0)
print(a_price == 1)

False
True


### If Statement Fundamentals

#### Instrucciones
En el editor de código, hemos proporcionado tres pares de declaraciones para su uso en este ejercicio. Recordemos que el código sangrado solo ejecuta cuando True sigue if. Cuando False sigue if, el código dentro del cuerpo no se ejecuta. Aprovechemos este comportamiento para imprimir solo las declaraciones donde ambos las declaraciones son ciertas.

Revise los pares de declaraciones proporcionadas en el editor de código.
Corrija el booleano después del if declaración cuando una o ambas declaraciones son falsas, de modo que el código dentro del cuerpo no se ejecuta.
Solo queremos imprimir declaraciones donde ambos las declaraciones son ciertas.

In [4]:
if False:
    print("2 + 2 == 5")
    print("lemons are sour")

if True:
    print("the sky is blue")
    print("5 >= 3")
    
if False:
    print("spheres have corners")
    print("7 / 5 == 2")

the sky is blue
5 >= 3


### 5 of 7 · The Average Rating of Non-free Apps

Modifique el código existente en el editor a la derecha para calcular la calificación promedio de las aplicaciones no libres.

Cambiar el nombre de la lista vacía de free_apps_ratings a non_free_apps_ratings (la lista que definimos antes del bucle for).
Cambia la condición if price == 0.0 para tener en cuenta el hecho de que ahora queremos aislar solo las calificaciones de las aplicaciones no libres.
Cambiar free_apps_ratings.append(rating) para asegurarse de que las calificaciones se adjuntan a la nueva lista non_free_apps_ratings.
Calcule el valor promedio sumando los valores en non_free_apps_ratings y dividiendo por la longitud de esta lista. Asigne el resultado a avg_rating_non_free.

Ejercicio opcional: Inspeccione el valor de avg_rating_non_free y compare el promedio con las aplicaciones gratuitas (la calificación promedio de las aplicaciones gratuitas es de aproximadamente 3.38 — lo calculamos en la primera pantalla). 

**¿Podemos usar los valores promedio para determinar si las aplicaciones gratuitas son mejores que las aplicaciones no gratuitas?**

In [5]:
# INITIAL CODE
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

non_free_apps_ratings = []
for row in apps_data[1:]:
    rating = float(row[7])
    price = float(row[4])   
    if price != 0.0:
        non_free_apps_ratings.append(rating)
    
avg_rating_non_free = sum(non_free_apps_ratings) / len(non_free_apps_ratings)
print(avg_rating_non_free)

3.720948742438714


### 6 of 7 · The Average Rating of Gaming Apps

Los operadores condicionales pueden funcionar de las siguientes maneras lo que hace que podamos responder a mas preguntas:

'''
print('Games' == 'Music')
print('Games' != 'Music')

Output 
False
True
'''

- ¿Cuál es la calificación promedio de las aplicaciones de juegos?
- ¿Cuál es la calificación promedio de las aplicaciones que no son de juegos?

Tenga en cuenta que el `prime_genre` la columna describe el género de la aplicación, y el género de las aplicaciones de juegos se codifica como `'Games'`.

Para calcular la calificación promedio de las aplicaciones de juegos, podemos usar el mismo enfoque que usamos en la pantalla anterior cuando calculamos la calificación promedio de las aplicaciones gratuitas y no gratuitas. En el ejemplo de código a continuación, hacemos lo siguiente:

- Inicializar una lista vacía llamada `games_ratings`.
    - Bucle a través `apps_data[1:]`, donde apps_data es una lista de listas que almacena nuestro conjunto de datos. Para cada iteración, hacemos lo siguiente:
    - Asigne la calificación como un `float` a una variable nombrada `rating`.
    - Asigne el género a una variable llamada genre y el género se guardará como una cuerda.
    - Añadir el valmor de calificación almacenado en rating a la lista `games_ratings` si el valor en genre es igual a 'Games'.
- Calcule la calificación promedio de las aplicaciones de juegos y asigne el resultado a `avg_rating_games`.
- Imprimir `avg_rating_games`.

In [6]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

non_free_apps_ratings = []
non_games_ratings = []
for row in apps_data[1:]:
    rating = float(row[7])
    price = float(row[4])   
    genero = row[11]
    
    if price != 0.0:
        non_free_apps_ratings.append(rating)
    if genero != 'Games':
        non_games_ratings.append(rating)

    
avg_rating_non_free = sum(non_free_apps_ratings) / len(non_free_apps_ratings)
print(avg_rating_non_free)


avg_rating_non_games = sum(non_games_ratings) / len(non_games_ratings)
print(avg_rating_non_games)

3.720948742438714
3.343928035982009


**Ejercicio opcional**: 

compare la calificación promedio de las aplicaciones de juegos (3.69) con la calificación promedio de las aplicaciones que no son de juegos. ¿Por qué crees que vemos esta diferencia?

### 1 of 9 · Multiple Conditions

Hasta ahora, solo hemos trabajado con condiciones individuales, como las siguientes:

- Si el precio es igual a 0.0 (`if price == 0`)
- Si el género es igual a "Juegos" (`if genre == 'Games'`)
  
Las condiciones individuales no nos permitirán responder preguntas más avanzadas, como estas:

- ¿Cuál es la calificación promedio de las aplicaciones de juegos gratuitas?
- ¿Cuál es la calificación promedio de las aplicaciones de juegos no libres?
- ¿Cuál es la calificación promedio de las aplicaciones gratuitas que no son de juegos?
- ¿Cuál es la calificación promedio de las aplicaciones no gratuitas que no son de juegos?



Afortunadamente, podemos combinar dos o más condiciones juntas en una sola `if` declaración usando el `and` palabra clave. En los dos diagramas a continuación, podemos usar `and` para verificar simultáneamente si una aplicación es gratuita y tiene un género de juego.

app_1_price = 0
app_1_genre = 'Games'

if app_1_price == 0 and app_1_genre == 'Games':
    print('This is a free game!')

print(app_1_price == 0 and app_1_genre == 'Games')

### Instrucciones

Complete el código en el editor para calcular la calificación promedio de las aplicaciones de juegos gratuitas.

- Dentro del bucle for, agregue la calificación al free_games_ratings lista si el precio es igual 0.0 y el género es igual 'Games'.

- Fuera del bucle for, calcule la calificación promedio de las aplicaciones de juegos gratuitas. Asigne el resultado a una variable nombrada avg_rating_free_games.

In [7]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

free_games_ratings = []
for row in apps_data[1:]:
    rating = float(row[7])
    price = float(row[4])
    genre = row[11]
    # Complete code from here
    if price == 0.0 and genre == 'Games':
        free_games_ratings.append(rating)

avg_rating_free_games = sum(free_games_ratings) / len(free_games_ratings)

print(avg_rating_free_games)

3.5285777580859548


## The or Operator

Si miramos las primeras cinco aplicaciones, podemos ver en el prime_genre columna que el género de Facebook es "Social Networking", mientras que el género de Clash of Clans y Temple Run es "Games"

Dado que las aplicaciones y los juegos de redes sociales suelen ser populares, es posible que deseemos investigar más a fondo esta categoría. Una cosa que podríamos querer determinar es la calificación promedio de esta categoría que abarca juegos y aplicaciones de redes sociales.

Para hacer eso, necesitamos aislar las calificaciones de todas las aplicaciones cuyo género es "Social Networking" o "Juegos" en una lista separada. Entonces, podemos calcular el valor promedio utilizando técnicas que ya conocemos.

Si queremos aislar las calificaciones de estas aplicaciones utilizando la condición `if genre == 'Social Networking' and genre == 'Games'`, terminaremos con una lista vacía porque no hay una aplicación con un género que sea "Social Networking" y "Games" — una aplicación solo puede tener un género.

Necesitamos aislar la calificación de una aplicación solo si el género es "Social Networking" `o` "Juegos," no "Redes Sociales" y "Juegos." Para tener en cuenta esta diferencia, podemos usar `or` en lugar de `and`:

```
for row in apps_data[1:]:
    rating = float(row[7])
    genre = row[11]

    if genre == 'Social Networking' or genre == 'Games':
        games_social_ratings.append(rating)

print(games_social_ratings[:5])
print(len(games_social_ratings))

<<output>>
[3.5, 4.5, 4.5, 4.5, 4.5]
4029

```

### Instrucciones

Complete el código en el editor para calcular la calificación promedio de las aplicaciones con un género que sea "Social Networking" o "Games."

Dentro del bucle for, agregue la calificación al games_social_ratings enumere si el género es tampoco 'Social Networking' o 'Games'. Fuera del bucle for, calcule la calificación promedio de las aplicaciones con un género que sea "Red Social" o "Juegos", y asigne el resultado a una variable llamada `avg_games_social`.

In [8]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

games_social_ratings = []
for row in apps_data[1:]:
    rating = float(row[7])
    genre = row[11]
    # Complete code from here
    if genre == 'Social Networking' or genre == 'Games':
        games_social_ratings.append(rating)

avg_games_social = sum(games_social_ratings) / len(games_social_ratings)
print(avg_games_social)

3.655994043186895


### 3 of 9 · Combining Logical Operators

En el ejercicio anterior, calculamos la calificación promedio de las aplicaciones con un género que es "Social Networking" o "Games." Podemos hacer preguntas aún más específicas, como estas:

- Cuál es la calificación promedio de gratis ¿aplicaciones con un género que es "Social Networking" o "Games"?
- Cuál es la calificación promedio de no es gratis ¿aplicaciones con un género que es "Social Networking" o "Games"?

Para responder a la primera pregunta, necesitamos aislar las aplicaciones que cumplen con ambos criterios:

Están en cualquiera de las "Redes Sociales" o Género "Juegos"
Tener un precio de 0.0

Para aislar estas aplicaciones, podemos combinar or con and en un solo if declaración:

```
free_games_social_ratings = []

for row in apps_data[1:]:
    rating = float(row[7])
    genre = row[11]
    price = float(row[4])

    if (genre == 'Social Networking' or genre == 'Games') and price ==0:
```

Observe que adjuntamos el genre == 'Social Networking' or genre == 'Games' parte entre paréntesis. Esto ayuda a Python a entender la lógica específica que queremos para nuestro if declaración.

```
# We want this logic:
if (genre == 'Social Networking' or genre == 'Games') and price ==0:

# Not this logic:
if genre == 'Social Networking' or (genre == 'Games' and price ==0):
```

Los parentesis indican orden de prioridad.

### Instrucciones

Calcule la calificación promedio de las aplicaciones no gratuitas con un género que sea "Redes Sociales" o "Juegos."

- Asigne el resultado a una variable nombrada `avg_not_free`.
- Intente completar este ejercicio sin ninguna orientación adicional. Puede sentirse un poco confundido al principio, pero hemos practicado los pasos que necesita para resolver este tipo de problema varias veces. Esencialmente, el código es casi idéntico a lo que usamos para extraer las calificaciones de los juegos gratuitos o las aplicaciones de redes sociales.

In [9]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

free_games_social_ratings = []
non_free_games_social_ratings = []

for row in apps_data[1:]:
    rating = float(row[7])
    genre = row[11]
    price = float(row[4])
    
    if (genre == 'Social Networking' or genre == 'Games') and price == 0:
        free_games_social_ratings.append(rating)
        
    if (genre == 'Social Networking' or genre == 'Games') and price != 0:
        non_free_games_social_ratings.append(rating)
        
avg_free = sum(free_games_social_ratings) / len(free_games_social_ratings)

# Not-free apps (average)
avg_not_free = sum(non_free_games_social_ratings) / len(non_free_games_social_ratings)

print(avg_free, avg_not_free)

3.496875 3.8904235727440146


### 4 of 9 · Comparison Operators

We can compare value A to value B to determine the following:

A is equal to B and vice versa (B is equal to A).
A is not equal to B and vice versa.
A is greater than B or vice versa.
A is greater than or equal to B or vice versa.
A is less than B or vice versa.
A is less than or equal to B or vice versa.

### Instructions
Convert the following statements to Python syntax:

If x is greater than z, print x is greater than z.
If y is not equal to z, print y is not equal to z.
If z is between x and y, print z is between x and y.
We've provided values for x, y and z in the code editor. Assume that y is bigger than x. Use these values to verify that only the true statements are printed. For answer checking purposes, do not include a period at the end of the statements.

In [10]:
x = -6
y = 14
z = 8.5

if x>z:
    print("x is greater than z")
if y!=z:
    print("y is not equal to z")
if  z>x and y>z:
    print("z is between x and y")

y is not equal to z
z is between x and y


### 5 of 9 · Comparison Operator Applications

Los operadores de comparación pueden ayudarnos a descubrir más sobre nuestros datos. Por ejemplo, podríamos querer saber:

- ¿Cuántas aplicaciones tienen una calificación de 4.0 o superior?
- Cuál es la calificación promedio de las aplicaciones que tienen un precio mayor que $¿9?
- Cuántas aplicaciones tienen un precio mayor que $¿9?
- Cuántas aplicaciones tienen un precio menor o igual a $¿9?

**Veamos dos formas de responder a la primera pregunta**.

**Primer enfoque, podemos:**

Crea una lista vacía llamada `apps_4_or_greater`.
Recorrer nuestros datos, excluyendo la fila de encabezado `(apps_data[1:])`.
En cada bucle, convierta la calificación a un número de punto flotante y guárdelo en una variable llamada `rating`.
Si rating es 4.0 o más, agréguelo al `apps_4_or_greater` list.
Una vez que se complete el bucle, cuente el número de elementos `apps_4_or_greater`. 
Esto nos dirá cuántas aplicaciones tienen una calificación de 4.0 o superior.

Así es como se ve en el código:

```
apps_4_or_greater = []

for row in apps_data[1:]:
    rating = float(row[7])
    if rating >= 4.0:
        apps_4_or_greater.append(rating)

print(len(apps_4_or_greater))

Output
4781

```

El segundo enfoque es similar, pero en lugar de almacenar las calificaciones en una lista, usaremos un contador:

Establecer una variable n_of_apps a 0.
Recorrer nuestros datos, excluyendo la fila de encabezado (apps_data[1:]).
En cada bucle, convierta la calificación a un número de punto flotante y guárdelo en una variable llamada rating.
Si rating es 4.0 o más, agregue 1 a n_of_apps.
Una vez que se complete el bucle, imprima n_of_apps. Esto nos dirá cuántas aplicaciones tienen una calificación de 4.0 o superior.
Aquí está el código:

```
n_of_apps = 0

for row in apps_data[1:]:
    rating = float(row[7])
    if rating >= 4.0:
        n_of_apps = n_of_apps + 1

print(n_of_apps)

Output
4781
```

Ahora respondamos las otras tres preguntas:

Cuál es la calificación promedio de las aplicaciones que tienen un precio mayor que $¿9?
Cuántas aplicaciones tienen un precio mayor que \$¿9?
Cuántas aplicaciones tienen un precio menor o igual a \$¿9?

### Instrucciones

1.Calcule la calificación promedio de las aplicaciones que cuestan más de \$9.

- Primero, haga una lista de calificaciones para todas las aplicaciones que cuestan más que \$9. Haga esto usando un bucle for para pasar apps_data, pero asegúrese de omitir la primera fila (que es el encabezado).
  
    - 1. A continuación, encuentre el promedio de estas calificaciones. Guarde su respuesta en una variable llamada avg_rating.
    - 2. Determine cuántas aplicaciones tienen un precio mayor que \$9 Y asigne el resultado a una variable nombrada n_apps_more_9. puede encontrar la respuesta contando el número de calificaciones en la lista que creó en el paso 1.

    - 3. Determine cuántas aplicaciones tienen un precio menor que o igual a \$9 Y asigne el resultado a una variable nombrada n_apps_less_9. La lista de calificaciones de la primera pregunta puede ayudarlo a encontrar una respuesta rápida.

In [11]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

apps_more_9 = []
apps_less_9 = []

for row in apps_data[1:]:
    rating = float(row[7])
    price = float(row[4])
    
    if price > 9:
        apps_more_9.append(rating)
    if price <= 9:
        apps_less_9.append(rating)

n_apps_more_9 = len(apps_more_9)

n_apps_less_9 = len(apps_less_9)

avg_rating = sum(apps_more_9)/len(apps_more_9)

print(n_apps_more_9,n_apps_less_9,avg_rating  )

178 7019 3.5280898876404496


### 6 of 9 · The else Clause

Usemos información del price columna para etiquetar cada aplicación como "gratis" o "no gratis." Si el precio es igual 0.0, queremos etiquetar la aplicación "gratis." De lo contrario, queremos etiquetarlo como "no libre."

Recuerde que nuestro conjunto de datos se mantiene en una estructura de lista de listas, donde cada lista individual representa una fila que contiene detalles sobre una aplicación específica.Queremos categorizar cada aplicación agregando una etiqueta al final de cada fila. Esta etiqueta será 'gratuita' o 'no gratuita', dependiendo de si la aplicación es gratuita o de pago. Para ayudar a ilustrar este proceso, considere un extracto simplificado de nuestro conjunto de datos, que incluye solo el names y prices de cuatro aplicaciones:

```
apps_data = [['Call of Duty: Zombies', 5.0], ['Facebook', 0.0], ['Instagram', 0.0], ['Temple Run', 0.0]]

for app in apps_data:
    price = app[1]

    if price == 0.0:
        app.append('free')
    if price != 0.0:
        app.append('not free')

print(apps_data)


[['Call of Duty: Zombies', 5.0, 'not free'], ['Facebook', 0.0, 'free'], ['Instagram', 0.0, 'free'], ['Temple Run', 0.0, 'free']]

```

En el código anterior, iteramos a través del `apps_data` lista de listas y para cada iteración completamos lo siguiente:

- Guardamos el valor del precio en una variable llamada price.
- Si price == 0.0, adjuntamos la cuerda 'free' a la lista app (app es la variable de iteración).
- Si price != 0.0, adjuntamos la cuerda 'not free' a la lista app.

Para cada iteración, la computadora verificó si price == 0.0 y price != 0.0. Después de descubrir que una aplicación es price == 0.0, no necesitamos verificar price != 0.0 para la misma aplicación.

En nuestro pequeño conjunto de datos anterior, hay 3 aplicaciones que son free. La computadora tiene que examinar si price == 0.0 para cada aplicación, que resulta ser True tres veces. Entonces tiene que comprobar si price != 0.0el mismo número de veces. Esto conduce a tres cálculos superfluos, a medida que la computadora todavía evalúa price != 0.0 aunque ya lo ha establecido price == 0.0 es True.

Imagine que tenemos un conjunto de datos más grande con 5,000 aplicaciones gratuitas. Esto daría como resultado 5.000 cálculos innecesarios. Podemos evitar esta ineficiencia utilizando un if declaración junto con una clausula else :


```
apps_data = [['Call of Duty: Zombies', 5.0], ['Facebook', 0.0], ['Instagram', 0.0], ['Temple Run', 0.0]]

for app in apps_data:
    price = app[1]

    if price == 0.0:
        app.append('free')
    else:
        app.append('not free')

print(apps_data)


[['Call of Duty: Zombies', 5.0, 'not free'], ['Facebook', 0.0, 'free'], ['Instagram', 0.0, 'free'], ['Temple Run', 0.0, 'free']]

```

### Instrucciones

Complete el código en el editor para etiquetar cada aplicación como "gratis" o "no gratis" dependiendo de su precio.

Dentro del bucle for, debe:

- Evalúa el precio de la aplicación. If el price es 0.0, usted debe clasificar la aplicación como "free". Haga esto agregando la cadena 'free' a la variable de iteración actual, que representa la aplicación actual.
  
- Else, si el price no lo es 0.0, usted debe clasificar la aplicación como "not free". Logre esto agregando la cuerda 'not free' a la variable de iteración actual. Tenga cuidado con la cadena y asegúrese de escribir 'not free' en lugar de 'not_free'.
  
- Después de completar este proceso para todas las aplicaciones, habrá agregado efectivamente una nueva columna a su conjunto de datos. Llamemos a esta columna free_or_not. Para hacer esto, agregue la cuerda free_or_not a la primera fila de la apps_data conjunto de datos, que normalmente representa la fila de encabezado. Este paso debe realizarse fuera del bucle for, ya que solo debe hacerse una vez.
  
Imprima la fila de encabezado y las primeras cinco filas para ver algunos de los cambios que hicimos.


In [12]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

for app in apps_data[1:]:
    price = float(app[4])
    # Complete code from here
    if price == 0.0:
        app.append("free")
    else:
        app.append("not free")

apps_data[0].append("free_or_not")

print(apps_data[0:3])

[['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic', 'free_or_not'], ['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1', 'free'], ['389801252', 'Instagram', '113954816', 'USD', '0.0', '2161558', '1289', '4.5', '4.0', '10.23', '12+', 'Photo & Video', '37', '0', '29', '1', 'free']]


### 7 of 9 · The elif Clause

Hagamos un etiquetado más específico que solo "gratis" y "no gratis." Queremos etiquetar las aplicaciones utilizando esta convención:


|precio	|etiqueta|
|:--|:--|
|precio == 0|	gratis|
|0 < precio < 20|	asequible|
|20 ≤ precio < 50|	caro|
|precio ≥ 50	|muy caro|


Usando lo que sabemos, solo podemos hacer las transformaciones anteriores usando una combinación de if declaraciones. Así se ve el proceso en el pequeño conjunto de datos a continuación:

```
apps_data = [['Facebook', 0.0], ['Notion', 14.99], ['Astropad Standard', 29.99], ['NAVIGON Europe', 74.99]]

for app in apps_data:
    price = app[1]

    if price == 0.0:
        app.append('free')
    if price > 0.0 and price < 20:
        app.append('affordable')
    if price >= 20 and price < 50:
        app.append('expensive')
    if price >= 50:
        app.append('very expensive')

print(apps_data)


[['Facebook', 0.0, 'free'], ['Notion', 14.99, 'affordable'], ['Astropad Standard', 29.99, 'expensive'], ['NAVIGON Europe', 74.99, 'very expensive']]

```

Para evitar que la computadora realice operaciones redundantes, podemos usar `elif`

```
apps_data = [['Facebook', 0.0], ['Notion', 14.99], ['Astropad Standard', 29.99], ['NAVIGON Europe', 74.99]]

for app in apps_data:
    price = app[1]

    if price == 0.0:
        app.append('free')
    elif price > 0.0 and price < 20:
        app.append('affordable')
    elif price >= 20 and price < 50:
        app.append('expensive')
    elif price >= 50:
        app.append('very expensive')

print(apps_data)


[['Facebook', 0.0, 'free'], ['Notion', 14.99, 'affordable'], ['Astropad Standard', 29.99, 'expensive'], ['NAVIGON Europe', 74.99, 'very expensive']]

```

### Instrucciones

El `app_ratings` de la variable proporcionada en el editor de código incluye información de calificación de usuario promedio para algunas aplicaciones. Usando `if` y `elif` , agregue una declaración que describa cómo se compara cada calificación de aplicación con la calificación promedio general de usuario de la totalidad AppleStore.csv conjunto de datos, que es 3.52.

Complete el código en el editor para etiquetar cada aplicación como "por debajo del promedio", "aproximadamente promedio" o "mejor que el promedio" dependiendo de su calificación.

Dentro del bucle for, complete lo siguiente:
Si la calificación de la aplicación es menor que 3.0, luego etiquete la aplicación como "por debajo del promedio" agregando la cadena 'below average' a la variable de iteración actual.
Si es así la calificación de la aplicación es mayor o igual a 3.0 y abajo 4.0, luego etiquete la aplicación como "aproximadamente promedio" agregando la cadena 'roughly average' a la variable de iteración actual.
Si es así la calificación de la aplicación es mayor o igual a 4.0 etiquete la aplicación "mejor que el promedio" agregando la cadena 'better than average' a la variable de iteración actual.
Imprimir app_ratings para ver los resultados.


In [13]:

app_ratings = [['Facebook', 3.5], ['Notion', 4.0], ['Astropad Standard', 4.5], ['NAVIGON Europe', 3.5]]

for app in app_ratings:
    if app[1] <=3:
        app.append("below average")
    elif app[1] >=3 and app[1]<4 :
        app.append("roughly average")
    elif app[1] >=4:
         app.append("better than average")

print(app_ratings)

[['Facebook', 3.5, 'roughly average'], ['Notion', 4.0, 'better than average'], ['Astropad Standard', 4.5, 'better than average'], ['NAVIGON Europe', 3.5, 'roughly average']]


### 8 of 9 · Else vs. elif

Es posible reemplazar la cláusula final elif  con una cláusula else . Para nuestros datos, la salida sería idéntica. Como recordatorio, así es como se ve el código elif como cláusula final:

```
apps_data = [['Facebook', 0.0], ['Notion', 14.99], ['Astropad Standard', 29.99], ['NAVIGON Europe', 74.99]]

for app in apps_data:
    price = app[1]

    if price == 0.0:
        app.append('free')
    elif price > 0.0 and price < 20:
        app.append('affordable')
    elif price >= 20 and price < 50:
        app.append('expensive')
    elif price >= 50:
        app.append('very expensive')

print(apps_data)

```

**elif (else if)**:

Significado: Se utiliza para verificar múltiples condiciones después de que se ha verificado una condición con if. Si la primera condición no se cumple, se pasa a la siguiente condición.

**else**:

Significado: Se utiliza como la última opción cuando ninguna de las condiciones anteriores ha sido verdadera. No depende de si alguna if o elif se ha evaluado antes.

Uso: Es útil cuando necesitas un "caso por defecto" que se aplicará si ninguna de las condiciones if o elif se cumple.


# Instrucciones
Complete el código en el editor para etiquetar cada aplicación como "gratis", "asequible," "caro," o "muy caro." Dentro del bucle, haga lo siguiente:

Si el precio de la aplicación es 0, etiquete la aplicación como "gratis" agregando la cadena 'free' a la variable de iteración actual.
Si el precio de la aplicación es mayor que 0 y menos que 20, etiquete la aplicación como "asequible". Para fines de eficiencia, use un elif cláusula.
Si el precio de la app es mayor o igual a 20 y menos que 50, etiquete la aplicación como "caro". Para fines de eficiencia, use un elif cláusula.
Si el precio de la app es mayor o igual a 50, etiquete la aplicación como "muy cara". Para fines de eficiencia, use un elif cláusula.
Nombra la columna recién creada "price_label" anexando la cadena 'price_label' a la primera fila de la apps_data conjunto de datos.

Inspeccione la fila del encabezado y las primeras cinco filas para ver algunos de los cambios que realizó.

In [14]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

for app in apps_data[1:]:
    price = float(app[4])
    # Complete code from here

In [15]:
from csv import reader

# Open the file and read it into a list of rows
opened_file = open('AppleStore.csv')
read_file = reader(opened_file)
apps_data = list(read_file)

# Add the 'price_label' column header to the first row
apps_data[0].append('price_label')

# Iterate over each app in the data and label it based on its price
for app in apps_data[1:]:
    price = float(app[4])
    
    if price == 0:
        app.append('free')
    elif price > 0 and price < 20:
        app.append('affordable')
    elif price >= 20 and price < 50:
        app.append('expensive')
    elif price >= 50:
        app.append('very expensive')

# Display the header row to see the changes
print(apps_data[0])

# Display the first five rows to see some of the label changes
for i in range(5):
    print(apps_data[i])

['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic', 'price_label']
['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic', 'price_label']
['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1', 'free']
['389801252', 'Instagram', '113954816', 'USD', '0.0', '2161558', '1289', '4.5', '4.0', '10.23', '12+', 'Photo & Video', '37', '0', '29', '1', 'free']
['529479190', 'Clash of Clans', '116476928', 'USD', '0.0', '2130805', '579', '4.5', '4.5', '9.24.12', '9+', 'Games', '38', '5', '18', '1', 'free']
['420009108', 'Temple Run', '65921024', 'USD', '0.0', '1724546', '3

# Python Dictionaries 1 of 7 · Storing Data

En esta lección aprenderemos cómo crear diccionarios, índices de diccionarios  y entender los pares clave-valor.

Trabajaremos con un conjunto de datos que almacena información para `7.197` aplicaciones móviles. 

Dentro de este conjunto de datos, la columna `cont_rating ` ofrece información sobre la calificación de contenido de cada aplicación. La calificación de contenido de una aplicación (también conocida como la calificación de madurez) representa la edad requerida para usar esa aplicación. 

La siguiente tabla muestra las calificaciones de contenido únicas en nuestro conjunto de datos, junto con el número de aplicaciones específicas para cada calificación:


|Calificación de contenido|	Número de aplicaciones|
|:--|:--|
|4+	|4.433|
|9+	|987|
|12+	|1.155|
|17+	|622|

De la tabla anterior, podemos ver lo siguiente:

La mayoría de las aplicaciones (4.433) tienen una calificación de contenido de 4+ (solo se recomienda a las personas de cuatro años o más que usen estas aplicaciones).

Aplicaciones con una calificación de contenido de 17+ son la menor cantidad (622).
En el medio, tenemos el 9+ y 12+ aplicaciones — 987 aplicaciones tienen una calificación de contenido de 9+ y 1,155 aplicaciones tienen una calificación de 12+.

Si queremos guardar los datos de la tabla anterior, podemos usar dos listas o una lista de listas que probaremos en el siguiente ejercicio. 

En la siguiente pantalla, aprenderemos sobre diccionarios y explore una solución más eficiente para almacenar los datos anteriores.

### Instrucciones

(El conjunto de datos está disponible en la pestaña csv en el editor a la derecha.)

1. Almacene los datos en la tabla anterior usando dos listas diferentes.

- Asigne la lista `['4+', '9+', '12+', '17+']` a una variable nombrada `content_ratings`.
- Asigne la lista `[4433, 987, 1155, 622]` a una variable nombrada `numbers`.

2. Almacene los datos en la tabla anterior usando una lista de listas. 

Asigne la lista `[['4+', '9+', '12+', '17+']`, `[4433, 987, 1155, 622]]` a una variable llamada `content_rating_numbers`.



In [16]:
content_ratings = ['4+', '9+', '12+', '17+']
numbers = [4433, 987, 1155, 622]

content_rating_numbers = [['4+', '9+', '12+', '17+'],[4433, 987, 1155, 622]]

### 2 de 7 ''Diccionarios

En la pantalla anterior, vimos una tabla que muestra las clasificaciones únicas de nuestro conjunto de datos, junto con el número de aplicaciones específicas para cada calificación:

Almacenamos los datos anteriores de dos maneras:

- Usando dos listas separadas
- Usando una sola lista de listas

```
# Two lists

content_ratings = ['4+', '9+', '12+', '17+']
numbers = [4433, 987, 1155, 622]

# A list of lists

content_rating_numbers = [['4+', '9+', '12+', '17+'], [4433, 987, 1155, 622]]
```

Al observar las listas anteriores, puede que no esté claro qué calificación de contenido corresponde a qué número.

Necesitamos encontrar una mejor manera de asignar una calificación de contenido a su número correspondiente.

Cada elemento de lista tiene un número de índice, eso ya lo sabía, pero ¿Qué pasaría si pudiéramos transformar los números de índice en valores de calificación de contenido? De esta manera, el mapeo entre las calificaciones de contenido y sus números correspondientes sería mucho más claro.

Afortunadamente, podemos hacer esto usando un diccionario:

```
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
print(content_ratings)


{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
```


Para crear el diccionario anterior, complete lo siguiente:

Asigne cada calificación de contenido a su número correspondiente siguiendo esta estructura: "index:value"

Por ejemplo, para asignar una calificación de `'4+'` al número `4.433`, escribimos `'4+': 4433`

Se escribe toda la secuencia:

`'4+': 4433, '9+': 987, '12+': 1155, '17+': 622`

y lo metemos entre llaves:

`{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622`}`

### Instrucciones
Asigne las calificaciones de contenido a sus números correspondientes recreando el diccionario anterior: 

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}. 

Asigne el diccionario a una variable nombrada `content_ratings`.
Imprimir content_ratings, y examinar la salida cuidadosamente.



In [17]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

print(content_ratings)

content_ratings['4+']

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


4433

### 3 de 7 ''Indexación

El uso de un diccionario nos permite (en este caso) cambiar los números de índice de una lista a los valores de calificación de contenido. 

De esta manera, el mapeo entre las calificaciones de contenido y sus números correspondientes se vuelve más claro.

### Instrucciones
Recuperar valores del diccionario `content_ratings` .

Asigne el valor en el índice `'9+'` a una variable nombrada `over_9`.

Asigne el valor en el índice `'17+'` a una variable nombrada `over_17`.

Imprimir `over_9` y `over_17`.

In [18]:
over_9 = content_ratings['9+']
over_17 = content_ratings['17+']

print(over_9)
print(over_17)

987
622


### 4 of 7 · Alternative Method of Creating a Dictionary

We can create a dictionary and populate it with values by following these steps:

Create an empty dictionary.
Add values one by one to that empty dictionary.

```
content_ratings = {} 
content_ratings['4+'] = 4433

print(content_ratings)

```
This approach is the same as populating an empty list by using the `list_name.append()` command. The syntax is different, but fundamentally we take the same steps:

Create an empty dictionary (or list).
Add values using the `dictionary_name[index] = value` technique (or the `list_name.append()` command in case of a list).

### Instructions

Use the new technique we learned to map content ratings to their corresponding numbers inside a dictionary.

Create an empty dictionary named `content_ratings`.

Add the index:value pairs one by one using the `dictionary_name[index] = value` technique. This should be the final form of the dictionary: `{'12+': 1155, '17+': 622, '4+': 4433, '9+': 987}`.

Retrieve the value at index `12+` from the `content_ratings` dictionary and assign it to a variable named `over_12_n_apps`.


In [19]:
content_ratings = {}

content_ratings['12+'] = 1155
content_ratings['17+'] = 622
content_ratings['4+'] = 4433
content_ratings['9+'] = 987

print(content_ratings)

over_12_n_apps = content_ratings['12+']

{'12+': 1155, '17+': 622, '4+': 4433, '9+': 987}


### 5 of 7 · Key-Value Pairs

A dictionary in Python is a collection of key-value pairs. Here's a breakdown of this concept:

**Key**: A unique identifier used to access a corresponding value.
**Value**:The data associated with a key.
**Key-Value Pair**:A combination of a key and its corresponding value.

Consider the key-value pair '4+': 4433. Here:

- **Key**: '4+'
- **Value**: 4433
  
Together, they form the key-value pair '4+': 4433.


Dictionary values can be of any data type: 

- strings, integers, floats, Booleans, lists, and even dictionaries.

Here's a dictionary containing different types of values:

<br>

```
d_1 = {'key_1': 'value_1', 
       'key_2': 1,
       'key_3': 1.832,
       'key_4': False,
       'key_5': [1,2,3],
       'key_6': {'inner_key' : 10}}

print(d_1)
print(d_1['key_1'])
print(d_1['key_6'])


Output
{'key_1': 'value_1', 'key_2': 1, 'key_3': 1.832, 
 'key_4': False, 'key_5': [1, 2, 3], 
 'key_6': {'inner_key': 10}}
value_1
{'inner_key': 10}

```

sin embargo mientras que los valores pueden ser casi cualquier cosa, las claves tienen algunas restricciones. 

They can be of many data types, including: integers, strings, floats, Booleans.

```
d_1 = {5: 'int',
       '5': 'string',
       3.5: 'float',
       False: 'Boolean'}

print(d_1)

```

However, lists and dictionaries cannot be used as keys. Attempting to do so results in a TypeError:

```
d_2 = {[1,2,3]: 'list'}
print(d_2)

Output
TypeError: unhashable type: 'list'


d_3 = {{'key': 'value'}: 'dictionary'}
print(d_3)

Output
TypeError: unhashable type: 'dict'

```
Esto se debe a que las claves deben ser "hashables", lo que significa que no pueden cambiar a lo largo de la vida útil del diccionario. Las listas y los diccionarios son mutables, por lo que no se pueden usar como claves.

### 6 of 7 · Key-Value Pairs Continued

Cuando rellenamos un diccionario, **Python intenta convertir cada clave de diccionario a un entero** (incluso si la clave es un tipo de datos que no sea un entero). Python hace la conversión usando el comando `hash()` :



Por razones que entenderemos más tarde, el comando hash() no transforma listas y diccionarios en enteros. Devuelve un error en su lugar. Observe que los mensajes de error son los mismos que cuando intentamos usar listas o diccionarios como claves.

Cuando rellenamos un diccionario, también debemos asegurarnos de que cada clave de ese diccionario sea única. Si usamos una clave idéntica para dos o más valores diferentes, Python mantiene solo la primera clave y el último valor y elimina los demás — esto significa que perderemos datos. A continuación ilustramos esto:

```
d_1 = {'a_key': 1,
       'another_key': 2,
       'a_key': 3,
       'yet_another_key': 4,
       'a_key': 5}

print(d_1)

Output
{'a_key': 5, 'another_key': 2, 'yet_another_key': 4}

```

Un "gotcha" extraño es cuando mezclamos enteros con booleanos como claves de diccionario. El hash() convierte al booleano True a 1 y el Booleano False a 0. Esto significa los Booleanos True y False entrará en conflicto con los enteros 0 y 1. 

Las teclas del diccionario ya no serán únicas, y Python solo mantendrá la primera clave y el último valor en casos como ese.

### Instrucciones

Cree el siguiente diccionario y asígnelo a una variable nombrada `d_1`:
```
{'key_1': 'first_value', 
 'key_2': 2,
 'key_3': 3.14,
 'key_4': True,
 'key_5': [4,2,1],
 'key_6': {'inner_key' : 6}
 }
```

In [20]:
d_1 = {'key_1': 'first_value', 
 'key_2': 2,
 'key_3': 3.14,
 'key_4': True,
 'key_5': [4,2,1],
 'key_6': {'inner_key' : 6}
 }

In [21]:
print(d_1)

{'key_1': 'first_value', 'key_2': 2, 'key_3': 3.14, 'key_4': True, 'key_5': [4, 2, 1], 'key_6': {'inner_key': 6}}


### Diccionarios de Python y Tablas de Frecuencia
1 de 10 ''Comprobación de la Membresía

En esta lección sobre diccionarios y tablas de frecuencia, aprenderemos cómo verificar la membresía del diccionario, actualizar los valores del diccionario y contar los valores usando diccionarios.

Una vez que hemos creado un diccionario, podemos **comprobar si un determinado valor se utiliza como clave en ese diccionario**. 

Por ejemplo, podemos comprobar si el valor `'12+'` es una clave en el diccionario `{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}`. Haces esto usando el `in`


In [22]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

print('12+' in content_ratings)

True


Comprobando si 4433 o 987 existe en content_ratings también devuelve False porque la búsqueda es solo para las claves del diccionario (4433 y 987 existe como diccionario valores en content_ratings).

In [23]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

print(4433 in content_ratings)
print(987 in content_ratings)

False
False


Una expresión de la forma `a_value` **in** `a_dictionary` siempre devuelve un valor booleano:

Tenemos `True` si `a_value` existe en `a_dictionary` como clave de diccionario.
Tenemos `False` si `a_value` no existe en `a_dictionary` como clave de diccionario.

Ahora practiquemos usando el operador `in`

### Instrucciones:

Usando el in operador, compruebe si los siguientes valores existen como claves de diccionario en el content_ratings diccionario:

La cadena de texto `'9+'`- Asigne la salida de la expresión a una variable nombrada `is_in_dictionary_1`.
El entero `987`- Asigne la salida de la expresión a una variable nombrada `is_in_dictionary_2`.
Combinar la salida de una expresión que contiene in con un if declaración. Si la cuerda `'17+'` existe como clave de diccionario en `content_ratings`, luego complete lo siguiente:

Asigne la cadena `"It exists`" a una variable nombrada `result`.
Imprimir la variable `result`.


In [24]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

is_in_dictionary_1 = '9+' in content_ratings

is_in_dictionary_2 = 987 in content_ratings

if ( '17+' in content_ratings) == True:
    print(content_ratings['17+'])
    result = "It exist"
    print(result)
    


622
It exist


### 2 of 10 · Updating Dictionary Values

Once we've created and populated a dictionary, we can update (change) the dictionary values. To update a dictionary value, we need to reference it by its corresponding dictionary key and then perform the updating operation we want. In the code example below, we do the following:

Change the value corresponding to the dictionary key `'4+'` from `4433` to `0`.

Add `13` to the value corresponding to the dictionary key `'9+'`.

Subtract `1155` from the value corresponding to the dictionary key `'12+'`.

Change the value corresponding to the dictionary key `'17+'` from `622` (integer) to `'622'` (string).

<br>

### Instructions

The `content_ratings` dictionary is corrupt and needs to be fixed. The corrupt version of `content_ratings` is provided in the code editor.

- Swap the values stored in the `4+` and `17+` keys.
- Assign the value stored in `4+` to a temporary variable called `temp`.
- Assign the value stored in `17+` to `4+`.
- Assign the value stored in the temporary variable to `17+`.
- Convert the value stored in `12+` into an integer.
- Print the `content_ratings dictionary`.

In [25]:
content_ratings = {'4+': 622, '12+': '1155', '9+': 987, '17+': 4433}

temp = content_ratings['4+']
content_ratings['4+'] = content_ratings['17+']  
content_ratings['17+']  = temp

content_ratings['12+'] = 1155


print(content_ratings)

{'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}


### 3 de 10 ''Contando con Diccionarios

Podemos actualizar los valores del diccionario para contar cuántas veces ocurre cada calificación de contenido único en nuestro conjunto de datos. Comencemos considerando la lista `['4+', '4+', '4+', '9+', '9+', '12+', '17+']`, que almacena algunas calificaciones de contenido. Para usar el código para contar cuántas veces ocurre cada calificación en esta breve lista, completemos lo siguiente:

Cree un diccionario donde las claves sean las clasificaciones de contenido únicas y los valores sean todos 0: `{'4+': 0, '9+': 0, '12+': 0, '17+': 0}`.
Recorre la lista `['4+', '4+', '4+', '9+', '9+', '12+', '17+']` y para cada iteración, haga lo siguiente:

Compruebe si la variable de iteración existe como una clave en el diccionario creado previamente.
Si existe, aumente el valor del diccionario en esa clave 1.

In [26]:
content_ratings = {'4+': 0, '9+': 0, '12+': 0, '17+': 0}
ratings = ['4+', '4+', '4+', '9+', '9+', '12+', '17+']

for c_rating in ratings:
    print(c_rating)
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1

print(content_ratings)

4+
4+
4+
9+
9+
12+
17+
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}


In [27]:
content_ratings = {'4+': 0, '9+': 0, '12+': 0, '17+': 0}
ratings = ['4+', '4+', '4+', '9+', '9+', '12+', '17+']

for c_rating in ratings:
    print(c_rating)
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1

print(content_ratings)

4+
4+
4+
9+
9+
12+
17+
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}


Ahora leamos en nuestro `AppleStore.csv` conjunto de datos y utilice la técnica anterior para contar el número de veces que se produce cada calificación de contenido único. Deberíamos llegar a los mismos números que hemos estado usando en la tabla:


|Calificación de contenido|	Número de aplicaciones|
|:--|:--|
|4+|	4.433|
|9+|	987|
|12+|	1.155|
|17+|	622|

### Instrucciones

- Cuente el número de veces que se produce cada calificación de contenido único en el conjunto de datos.
  
    - 1. Crea un diccionario llamado `content_ratings` donde las claves son las clasificaciones de contenido únicas y los valores son todos 0 (los valores de 0 son temporales en este punto, y se actualizarán).
         
    - 2. Bucle a través del apps_data lista de listas y asegúrese de no incluir la fila de encabezado. Para cada iteración del bucle, haga lo siguiente:
         
            - Asigne el valor de calificación de contenido a una variable nombrada c_rating. La calificación de contenido está en el número de índice 10 en cada fila.
              
            - Compruebe si `c_rating` existe como una clave en `content_ratings`. Si existe, aumente el valor del diccionario en esa clave 1 (la clave es equivalente al valor almacenado en c_rating).
              
    - 3.Fuera del bucle, imprima `content_ratings` para comprobar si el conteo funcionó como se esperaba.

In [28]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

print(apps_data[0])

['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic']


In [29]:
content_ratings = {'4+':0,'9+':0,'12+':0,'17+':0}


for apps in apps_data[1:]:
    if apps[10] in content_ratings:
        content_ratings[str(apps[10])] += 1
    else:
        content_ratings[str(apps[10])] = str(apps[7]) 

print(content_ratings)

{'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}


### Desafortunadamente, este enfoque requiere que conozcamos los valores únicos que queremos contar de antemano.

Necesitamos una forma de extraer esta información.


Consideremos nuevamente el recuento que hicimos para la lista `['4+', '4+', '4+', '9+', '9+', '12+', '17+']`. Para realizar el conteo mientras encontramos los valores únicos automáticamente, haremos lo siguiente:

- Crea un diccionario vacío llamado `content_ratings`.
- Recorre la lista `['4+', '4+', '4+', '9+', '9+', '12+', '17+']` y compruebe para cada iteración donde la variable de iteración `(c_rating)` existe como una clave en `content_ratings`.
- Si existe, aumente el valor del diccionario en esa clave `1`.
- De lo contrario (si no existe), cree un nuevo par clave-valor en el `content_ratings` diccionario, donde la clave del diccionario es la variable de iteración `(c_rating)` y el valor del diccionario es 1.

In [30]:
content_ratings = {}
ratings = ['4+', '4+', '4+', '9+', '9+', '12+', '17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1

print(content_ratings)

{'4+': 3, '9+': 2, '12+': 1, '17+': 1}


Puede preguntarse por qué creamos cada clave de diccionario con un valor de diccionario de 1 en lugar de 0. 

Cuando nos encontramos con una calificación de contenido, necesitamos contarla, ya sea que ya exista como una clave de diccionario o no. Cuando entra una calificación que aún no está en el diccionario, necesitamos inicializarla y contarla. Necesitamos inicializarlo con un valor de 1 para marcar el hecho de que esta calificación ya ha ocurrido una vez. Si inicializamos la clave del diccionario con un valor de 0 éxito en la inicialización, pero fracasamos en el conteo.

Para una imagen más clara de lo que hicimos anteriormente, imprimiremos el content_rating diccionario dentro del bucle for para ver como cambia con cada iteración:

In [31]:
content_ratings = {}
ratings = ['4+', '4+', '4+', '9+', '9+', '12+', '17+']

for c_rating in ratings:
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1
    print(content_ratings)

print('Final dictionary:')
print(content_ratings)

{'4+': 1}
{'4+': 2}
{'4+': 3}
{'4+': 3, '9+': 1}
{'4+': 3, '9+': 2}
{'4+': 3, '9+': 2, '12+': 1}
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}
Final dictionary:
{'4+': 3, '9+': 2, '12+': 1, '17+': 1}


### Instrucciones como extraer los valores sin saberlos de antemano

Cuente el número de veces que se produce cada calificación de contenido único en el conjunto de datos mientras encuentra los valores únicos automáticamente.

- 1. Crea un diccionario vacío llamado content_ratings.
- 2. Bucle a través del apps_data lista de listas (no incluya la fila de encabezado). Para cada iteración del bucle, complete lo siguiente:
    - Asigne el valor de calificación de contenido a una variable nombrada c_rating. La calificación de contenido está en el número de índice 10.
    - Compruebe si c_rating existe como una clave en content_ratings.
Si existe, aumente el valor del diccionario en esa clave 1 (la clave es equivalente al valor almacenado en c_rating).
    - De lo contrario, cree un nuevo par clave-valor en el diccionario, donde está la clave del diccionario c_rating y el valor del diccionario es 1.
- 3. Fuera del bucle, imprima content_ratings para comprobar si el conteo funcionó como se esperaba.


In [32]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

content_ratings = {}

for rating in apps_data[1:]:
    print(rating[10])
    if rating[10] in content_ratings:
        content_ratings[rating[10]] +=1
    else:
        content_ratings[rating[10]] =1

#content_ratings

4+
12+
9+
9+
12+
12+
4+
4+
12+
4+
9+
4+
4+
4+
9+
12+
4+
17+
9+
4+
4+
4+
4+
4+
17+
9+
12+
4+
9+
4+
12+
4+
12+
9+
4+
12+
12+
4+
4+
4+
17+
4+
4+
4+
4+
4+
4+
17+
4+
4+
4+
17+
4+
12+
12+
4+
4+
12+
9+
4+
12+
4+
4+
4+
4+
17+
4+
12+
9+
9+
4+
12+
12+
4+
9+
4+
9+
4+
4+
9+
12+
4+
4+
4+
12+
4+
4+
4+
9+
4+
4+
12+
4+
4+
17+
4+
12+
4+
4+
9+
17+
4+
4+
12+
12+
4+
4+
4+
12+
12+
17+
4+
9+
4+
12+
4+
4+
4+
4+
12+
4+
9+
4+
4+
4+
4+
12+
4+
4+
12+
12+
12+
12+
4+
4+
4+
17+
4+
4+
9+
12+
17+
12+
17+
4+
4+
4+
4+
12+
12+
4+
4+
12+
4+
4+
4+
4+
4+
4+
4+
4+
4+
4+
4+
4+
4+
12+
12+
4+
4+
4+
4+
9+
4+
4+
4+
9+
4+
4+
12+
4+
17+
17+
4+
12+
4+
4+
12+
4+
4+
9+
12+
4+
12+
12+
4+
4+
9+
4+
9+
4+
4+
4+
4+
4+
4+
4+
12+
4+
4+
4+
17+
4+
4+
12+
9+
4+
4+
4+
12+
4+
4+
17+
9+
12+
12+
17+
4+
4+
4+
9+
4+
12+
4+
4+
12+
4+
4+
4+
4+
9+
4+
4+
4+
4+
12+
9+
4+
4+
4+
4+
4+
12+
4+
12+
12+
4+
17+
12+
4+
4+
4+
4+
4+
4+
4+
4+
17+
4+
12+
12+
4+
12+
4+
4+
4+
12+
12+
4+
9+
9+
17+
4+
4+
4+
4+
4+
4+
4+
4+
12+
4+
17+
12+
4+
4+
4+
17+
17+
4+
4+
4+
4+
12+


### 5 of 10 · Proportions and Percentages

Al numero de veces que se repite un valor único, se le llama frecuencia.


|Calificación de contenido	|Número de aplicaciones (frecuencia)|
|:--|:--|
|4+	|4.433|
|9+	|987|
|12+	|1.155|
|17+	|622|


4+ ocurre 4.433 veces, por lo que tiene una frecuencia de 4.433. 12+ tiene una frecuencia de 1.155. 9+ tiene una frecuencia de 987. 17+ tiene la frecuencia más baja: 622.

Cuando estamos analizando frecuencias, es posible que queramos responder preguntas sobre **proporciones y porcentajes**:

- Qué proporción de aplicaciones tienen una calificación de contenido de 4+?
- Qué porcentaje de aplicaciones tienen una calificación de contenido de 17+?
 -¿Qué porcentaje de aplicaciones puede descargar un niño de 15 años?

Por supuesto, permíteme explicarlo de manera más clara y detallada.

En este caso, se está calculando la proporción o el porcentaje de aplicaciones que tienen una calificación de contenido de `4+` en un conjunto total de aplicaciones. 

Aquí hay una explicación paso a paso:

- 1. **Número de aplicaciones con calificación `4+`:** Se menciona que hay 4,433 (cuatro mil cuatrocientas treinta y tres) aplicaciones que tienen una calificación de contenido de `4+`.

- 2. **Total de aplicaciones:** También se indica que hay 7,197 (siete mil onecientos noventa y siete) aplicaciones en total.

- 3. **Proporción calculada:** Para encontrar la proporción de aplicaciones con una calificación de contenido de `4+`, se divide el número de aplicaciones con calificación `4+` por el número total de aplicaciones.
   - Esto se escribe matemáticamente como: $(\frac{4,433}{7,197}$\).

- 4. **Resultado de la proporción:** Al realizar esta división, obtenemos el resultado que se menciona en la oración final:
   - La proporción de aplicaciones con calificación `4+` es $( \frac{4,433}{7,197} $\).


Esto significa que aproximadamente alrededor del **61.8%** de las aplicaciones tienen una calificación de contenido de `4+`. Sin embargo, el valor exacto en fracción no se proporciona; solo se muestra la forma como fue calculada.

Si quisieras convertirlo a un porcentaje, podrías multiplicar $(\frac{4,433}{7,197}$\) aproximadamente por **100*:
- $( \frac{4,433}{7,197} \approx 0.618 $\), y al multiplicarlo por **100**: $( 0.618 \times 100 = 61.8\% $\).

### Instrucciones:

Cuente el número de veces que ocurre cada género único.
- 1. Crea un diccionario vacío llamado `genre_counting`.
- 2. Bucle a través del `apps_data` lista de listas (no incluya la fila de encabezado). Para cada iteración del bucle, haz lo siguiente:

        - Asigne el género a una variable llamada `genre`. El género viene como una cadena y tiene el número de índice 11.
        - Compruebe si `genre` existe como una clave en `genre_counting`.
        - Si existe, aumente el valor del diccionario en esa clave en 1 (la clave es equivalente al valor almacenado en `genre`).
        - De lo contrario, cree un nuevo par clave-valor en el diccionario, donde está la clave del diccionario `genre` y el valor del diccionario es 1.
  
- 3. Fuera del bucle, imprime `genre_counting` e intente determinar el género de aplicaciones más común en nuestro conjunto de datos.

In [33]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

genre_counting = {}

for genre in apps_data[1:]:
    if genre[11] in genre_counting:
        genre_counting[genre[11]] +=1
    else:
        genre_counting[genre[11]] =1

print(genre_counting)

{'Social Networking': 167, 'Photo & Video': 349, 'Games': 3862, 'Music': 138, 'Reference': 64, 'Health & Fitness': 180, 'Weather': 72, 'Utilities': 248, 'Travel': 81, 'Shopping': 122, 'News': 75, 'Navigation': 46, 'Lifestyle': 144, 'Entertainment': 535, 'Food & Drink': 63, 'Sports': 114, 'Book': 112, 'Finance': 104, 'Education': 453, 'Productivity': 178, 'Business': 57, 'Catalogs': 10, 'Medical': 23}


### 6 of 10 · Looping over Dictionaries

Para cambiar las frecuencias en proporciones o porcentajes, podemos modificar individualmente los valores en el diccionario haciendo las matemáticas necesarias. En el siguiente ejemplo, dividimos cada valor en el diccionario por el número total de aplicaciones para cambiar las frecuencias en proporciones.

In [34]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
total_number_of_apps = 7197

content_ratings['4+'] /= total_number_of_apps
content_ratings['9+'] /= total_number_of_apps
content_ratings['12+'] /= total_number_of_apps
content_ratings['17+'] /= total_number_of_apps

print(content_ratings)

{'4+': 0.6159510907322495, '9+': 0.13714047519799916, '12+': 0.16048353480616923, '17+': 0.08642489926358204}


Actualizar manualmente cada valor en el diccionario puede llevar mucho tiempo, especialmente si el diccionario es grande. Por ejemplo, con 20 pares clave-valor, tendríamos que actualizar 20 valores a mano. Afortunadamente, podemos hacer que este proceso sea más rápido usando un bucle for.

In [35]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

for iteration_variable in content_ratings:
    print(iteration_variable)

4+
9+
12+
17+


Luego podemos usar estas claves para obtener los valores dentro del bucle:



In [36]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}

for iteration_variable in content_ratings:
    print(iteration_variable)
    print(content_ratings[iteration_variable])

4+
4433
9+
987
12+
1155
17+
622


Esto nos permite cambiar los valores dentro del bucle. Así es como podemos cambiar las frecuencias en proporciones usando un bucle:

In [37]:
content_ratings = {'4+': 4433, '9+': 987, '12+': 1155, '17+': 622}
total_number_of_apps = 7197

for iteration_variable in content_ratings:
    content_ratings[iteration_variable] /= total_number_of_apps

print(content_ratings)

{'4+': 0.6159510907322495, '9+': 0.13714047519799916, '12+': 0.16048353480616923, '17+': 0.08642489926358204}


Practiquemos esta técnica haciendo algunos ejercicios. Comience respondiendo las dos preguntas que dejamos sin respuesta en la pantalla anterior:

- Qué porcentaje de aplicaciones tiene una calificación de contenido de '17+'?
- ¿Qué porcentaje de aplicaciones puede descargar un niño de 15 años?
  

In [38]:
content_ratings = {'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
total_number_of_apps = 7197
percentage_15_allowed = 0
percentage_17_plus = 0

for rating in content_ratings:
    content_ratings[rating] /= total_number_of_apps
    content_ratings[rating] *= 100
    if rating == '17+':
        percentage_17_plus += content_ratings[rating]
        print(rating)
    else:
        percentage_15_allowed += content_ratings[rating]


print(percentage_17_plus)
print(percentage_15_allowed)
    

print(content_ratings)

17+
8.642489926358204
91.35751007364179
{'4+': 61.595109073224954, '12+': 16.04835348061692, '9+': 13.714047519799916, '17+': 8.642489926358204}


In [39]:
percentage_17_plus = 8.642489926358204
print(percentage_15_allowed)

91.35751007364179


### 7 of 10 · Keeping the Dictionaries Separate

Anteriormente, transformamos las frecuencias en proporciones o porcentajes sobrescribiendo los valores iniciales del diccionario. Sin embargo, a menudo tendremos que mantener los diccionarios separados para su posterior análisis. Por ejemplo, es posible que deseemos tener tres diccionarios separados: uno para almacenar frecuencias, otro para almacenar proporciones y otro para almacenar porcentajes.

Cuando transformamos frecuencias en proporciones, podemos crear un nuevo diccionario en lugar de sobrescribir los valores en el diccionario inicial. Para hacer eso, podemos crear un nuevo diccionario vacío y rellenarlo dentro del bucle:

In [40]:
content_ratings = {'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
total_number_of_apps = 7197
c_ratings_proportions = {}

for key in content_ratings:
    proportion = (content_ratings[key] / total_number_of_apps)     
    c_ratings_proportions[key] = proportion

print(c_ratings_proportions)
print(content_ratings)

{'4+': 0.6159510907322495, '12+': 0.16048353480616923, '9+': 0.13714047519799916, '17+': 0.08642489926358204}
{'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}


Para ver cómo funciona esto, imprimiremos:

`la variable de iteración`, `la proporción` y `el nuevo diccionario para cada iteración`:

In [41]:
content_ratings = {'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
total_number_of_apps = 7197
c_ratings_proportions = {}

for key in content_ratings:
    proportion = (content_ratings[key] / total_number_of_apps)     
    print('Key:', key)
    print('Proportion value:', proportion)

    c_ratings_proportions[key] = proportion
    print(c_ratings_proportions)

Key: 4+
Proportion value: 0.6159510907322495
{'4+': 0.6159510907322495}
Key: 12+
Proportion value: 0.16048353480616923
{'4+': 0.6159510907322495, '12+': 0.16048353480616923}
Key: 9+
Proportion value: 0.13714047519799916
{'4+': 0.6159510907322495, '12+': 0.16048353480616923, '9+': 0.13714047519799916}
Key: 17+
Proportion value: 0.08642489926358204
{'4+': 0.6159510907322495, '12+': 0.16048353480616923, '9+': 0.13714047519799916, '17+': 0.08642489926358204}


### Instrucciones

Transforma las frecuencias en el interior `content_ratings` a proporciones y porcentajes mientras se crean diccionarios separados para cada uno.

- Asigne el diccionario que almacena las proporciones a una variable nombrada `c_ratings_proportions`.
  
- Asigne el diccionario que almacena porcentajes a una variable nombrada `c_ratings_percentages`.
  
- Desafío opcional: intente resolver este ejercicio utilizando un solo bucle for (solución a este desafío proporcionada).

In [42]:
content_ratings = {'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
total_number_of_apps = 7197
c_ratings_proportions = {}
c_ratings_percentages = {}

for key in content_ratings:
    proportion = (content_ratings[key]/total_number_of_apps)
    c_ratings_proportions[key] = proportion
    percentage = proportion*100
    c_ratings_percentages[key] = percentage
    
print(c_ratings_proportions)
print(c_ratings_percentages)

{'4+': 0.6159510907322495, '12+': 0.16048353480616923, '9+': 0.13714047519799916, '17+': 0.08642489926358204}
{'4+': 61.595109073224954, '12+': 16.04835348061692, '9+': 13.714047519799916, '17+': 8.642489926358204}


### 8 de 10 Tablas de Frecuencia para Columnas Numéricas

La creación de tablas de frecuencia para ciertas columnas puede dar lugar a largos diccionarios debido a la gran cantidad de valores únicos. Por ejemplo, considere la columna `size_bytes`  (la tercera columna en la tabla a continuación), que describe el tamaño de los datos de una aplicación:

|id	|track_nombre	|tamaño_bytes|	
|:--|:--|:--|
|284882215	|Facebook	|389879808	|
|389801252	|Instagram	|113954816	|
|529479190	|Choque de Clanes	|116476928|

A continuación, generamos una tabla de frecuencias para la columna `size_bytes` . 
Vemos que hay 7.107 pares clave-valor en el diccionario resultante.

In [43]:
size_freq = {}

for row in apps_data[1:]:
    size = row[2]

    if size in size_freq:
        size_freq[size] +=1
    else:
        size_freq[size] = 1

print(len(size_freq))
#print(size_freq)

7107


La salida anterior está truncada porque es larga. 

Una tabla de frecuencia larga es difícil de analizar. Cuanto más larga sea la tabla, más difícil será identificar patrones. Como solución alternativa, podemos crear intervalos bien definidos y contar la frecuencia para esos intervalos. 

Por ejemplo, es posible que deseemos crear cinco intervalos para el size_bytes columna y luego cuente el número de aplicaciones específicas para cada intervalo.

|Tamaño de datos (bytes)	|Frecuencia|
|:--|:--|
|0 - 10.000.000 (0 - 10 MB)	|285|
|10.000.000 - 50.000.000 (10 - 50 MB)| 1.639|
|50,000,000 - 100,000,000 (50 - 100 MB) |	1.778|
|100.000.000 - 500.000.000 (100 - 500 MB)|	2.894|
|500,000,000+ (500+ MB)	|601|

El uso de intervalos nos ayuda a segmentar los datos en grupos, lo que facilita el análisis. 

Mirando la tabla anterior, podemos ver que la mayoría de las aplicaciones tienen entre 100 y 500 MB, la menor cantidad de aplicaciones tienen menos de 10 MB, etc.

Elegir intervalos no siempre es sencillo. Arriba, elegimos los intervalos principalmente en función de nuestro conocimiento de los tamaños de datos comunes para las aplicaciones telefónicas. Si no tuviéramos esta información, tendríamos que confiar en otra cosa para determinar intervalos sensatos.

Cuando estamos tratando de llegar a algunos intervalos razonables, a menudo ayuda a conocer los valores mínimos y máximos de una columna. Esto nos ayuda a determinar dónde deben comenzar los intervalos y dónde deben terminar.

Para determinar los valores mínimo y máximo de una columna, podemos usar `min()` y el `max()`. 

Estos dos comandos descubren los valores mínimo y máximo para cualquier lista de enteros o en coma flotante.


In [44]:
a_list = [1, 20, 10.5, 4, 0]

print(max(a_list))
print(min(a_list))

20
0


In [45]:
# min() and max() do not work properly for strings
a_list = ['1', '20', '10.5', '4', '0']

print(max(a_list))
print(min(a_list))

4
0


Para determinar el tamaño mínimo y máximo de los datos de la aplicación, necesitamos extraer los valores en la columna `size_bytes` en coma flotante  o enteros en una lista separada, y luego use los comandos `min()` y el `max()` comandos en esa lista. 

Haremos esto en el ejercicio a continuación y reanudaremos esta discusión en la siguiente pantalla.

### Instrucciones

- 1. Extraer los valores de la columna `size_bytes` en una lista separada.
    - Crea una lista vacía llamada `data_sizes`.
    - Bucle a través `apps_data` (no incluya la fila de encabezado) y para cada iteración, haga lo siguiente:
    - Almacene el tamaño de los datos como un flotador en una variable llamada `size` (el número de índice para el tamaño de los datos es 2).
    - Apéndice `size` a la  `data_sizes` lista.
      
      <br>
      
- 2. Determine el tamaño mínimo y máximo de los datos de la aplicación.
        - Asigne el valor mínimo a una variable nombrada `min_size`.
        - Asigne el valor máximo a una variable nombrada `max_size`.

In [46]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

data_sizes = []

for data in apps_data[1:]:
    size = float(data[2])
    data_sizes.append(size)

print(min(data_sizes))
print(max(data_sizes))

min_size = min(data_sizes)
max_size = max(data_sizes)

589824.0
4025969664.0


### 9 de 10 ''Filtrado para los Intervalos

Basándonos en los valores que encontramos en el ejercicio anterior, usemos estos intervalos para el size_bytes columna (tenga en cuenta que los valores mínimos y máximos solo informaron nuestra elección — no necesariamente tienen que ser el punto inicial y final de los intervalos):

|Tamaño de datos (bytes)|
|:--|
|0 - 10.000.000 (0 - 10 MB)	|
|10.000.000 - 50.000.000 (10 - 50 MB)|
|50,000,000 - 100,000,000 (50 - 100 MB) |
|100.000.000 - 500.000.000 (100 - 500 MB)|
|500,000,000+ (500+ MB)	|

Una vez que conocemos los intervalos que queremos, podemos continuar calculando la frecuencia para cada intervalo.

|Tamaño de datos (bytes)	|Frecuencia|
|:--|:--|
|0 - 10.000.000 (0 - 10 MB)	|?|
|10.000.000 - 50.000.000 (10 - 50 MB)| ?|
|50,000,000 - 100,000,000 (50 - 100 MB) |	?|
|100.000.000 - 500.000.000 (100 - 500 MB)|	?|
|500,000,000+ (500+ MB)	|?|

Queremos almacenar la tabla de frecuencias como un diccionario. Comenzamos creando un diccionario con los intervalos como claves de diccionario y frecuencias como valores de diccionario (inicializamos todas las frecuencias con cero):

In [47]:
data_sizes = {'0 - 10 MB': 0, '10 - 50 MB': 0, '50 - 100 MB': 0,
                    '100 - 500 MB': 0, '500 MB +': 0}

A continuación, realizamos un bucle a través de nuestro conjunto de datos. Para cada iteración, haga lo siguiente:

- Almacene el tamaño de los datos como un flotador en una variable llamada `data_size`
- Determine a qué intervalo pertenece el tamaño de los datos utilizando una declaración `if` seguida de una serie de `elif` (usamos `elif` para evitar cálculos redundantes).
- Aumente la frecuencia en nuestro diccionario por 1 dependiendo del intervalo al que pertenezca el tamaño de los datos.

In [48]:
data_sizes = {'0 - 10 MB': 0, '10 - 50 MB': 0, '50 - 100 MB': 0,
                    '100 - 500 MB': 0, '500 MB +': 0}

for row in apps_data[1:]:
    data_size = float(row[2])

    if data_size <= 10000000:
        data_sizes['0 - 10 MB'] += 1

    elif 10000000 < data_size <= 50000000:
        data_sizes['10 - 50 MB'] += 1

    elif 50000000 < data_size <= 100000000:
        data_sizes['50 - 100 MB'] += 1

    elif 100000000 < data_size <= 500000000:
        data_sizes['100 - 500 MB'] += 1

    elif data_size > 500000000:
        data_sizes['500 MB +'] += 1


print(data_sizes)

{'0 - 10 MB': 285, '10 - 50 MB': 1639, '50 - 100 MB': 1778, '100 - 500 MB': 2894, '500 MB +': 601}


Ahora practiquemos esta técnica creando una tabla de frecuencias para el `rating_count_tot` columna, que describe el número total de calificaciones de usuarios que ha recibido una aplicación.

El siguiente ejercicio ofrece menos orientación que los ejercicios anteriores. Si se queda atascado en algún momento, comience revisando las partes relevantes del material que hemos cubierto hasta ahora. Quedarse atascado es parte del proceso, así que no se desanime.

In [49]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

rtng_count = []
for apps in apps_data[1:]:
    rtng_count.append(int(apps[5]))

print(min(rtng_count))
print(max(rtng_count))

0
2974676


In [50]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)


n_user_ratings = []
for row in apps_data[1:]:
    n_user_ratings.append(int(row[5]))
    
ratings_max = max(n_user_ratings)
ratings_min = min(n_user_ratings)

user_ratings_freq = {'0 - 10000': 0, '10000 - 100000': 0, '100000 - 500000': 0,
                    '500000 - 1000000': 0, '1000000+': 0}

for row in apps_data[1:]:
    user_ratings = int(row[5])
    
    if user_ratings <= 10000:
        user_ratings_freq['0 - 10000'] += 1
        
    elif 10000 < user_ratings <= 100000:
        user_ratings_freq['10000 - 100000'] += 1
        
    elif 100000 < user_ratings <= 500000:
        user_ratings_freq['100000 - 500000'] += 1
        
    elif 500000 < user_ratings <= 1000000:
        user_ratings_freq['500000 - 1000000'] += 1
        
    elif user_ratings > 1000000:
        user_ratings_freq['1000000+'] += 1


print(user_ratings_freq)

{'0 - 10000': 6181, '10000 - 100000': 798, '100000 - 500000': 196, '500000 - 1000000': 16, '1000000+': 6}


### 1 of 7 · Functions

### Instructions

Generate a frequency table for the ratings list (which is already initialized in the code editor).

Start by creating an empty dictionary named content_ratings.
Loop through the ratings list. For each iteration, complete the following:
If the rating is already in content_ratings, then increment the frequency of that rating by 1.
Else, initialize the rating with a value of 1 inside the content_ratings dictionary.
Print content_ratings.

In [51]:
ratings = ['4+', '4+', '4+', '9+', '12+', '12+', '17+', '17+']

content_ratings = {}

for rating in ratings:
    if rating in content_ratings:
        content_ratings[rating] +=1
    else:
        content_ratings[rating] =1

print(content_ratings)

{'4+': 3, '9+': 1, '12+': 2, '17+': 2}


### 3 of 7 · Creating Our Own Functions

Recreate the `square()` function above and compute the square for numbers 10 and 16

In [52]:
def square(a):
    sq = a * a
    return sq

In [53]:
print(square(8))

64


### 4 of 7 · The Structure of a Function

### Instructions

Create a function named `add_10()` that does the following:

- Toma un número como entrada (nombra la variable de entrada como desees)

- Agrega el entero 10 a ese número
- Devuelve el resultado de la adición

  
Use the `add_10()` function to do the following:

- Añadir  10 al número  30 — asigna el resultado a una variable nombrada `add_30`
- Añadir  10 al número  90 — asigna el resultado a una variable nombrada `add_90`

In [54]:
def add_10(a):
    return a+10

add_30 = add_10(10)
add_90 = add_10(90)

print(add_30, add_90)

20 100


### 5 de 7 ''Parámetros y Argumentos

En la programación, una función sirve como un bloque de código autónomo diseñado para realizar una tarea específica. Una función toma entrada, la procesa y produce salida. Para especificar el tipo de entrada con la que debería funcionar una función, utilizamos construcciones conocidas como "Parámetros" y "Argumentos.

Cuando definimos una función, a menudo incluimos algunas variables como marcadores de posición para las entradas futuras que recibirá la función. Estas variables se llaman parámetros.

In [55]:
def square(a_number):
    squared_number = a_number * a_number
    return squared_number

Cuando definimos una función, a menudo incluimos algunas variables como marcadores de posición para las entradas futuras que recibirá la función. Estas variables se llaman **parámetros**.

Ahora, cuando usamos la función, reemplazamos este marcador de posición con datos reales. Estos datos reales se llaman un **argumento**.

Proporcionamos una función llamada date() en el editor de código. Esta función actualmente toma entradas month y day y los devuelve juntos en una cadena. Queremos el date() función para devolver el año, así como el mes y el día.

1. Modificar el date() función para agregar un year parámetro:

In [56]:
def date(month, day, year):
    return str(day) + " " + str(month) +", "+ str(year)

In [57]:
print(date(15,'July',2006))
print(date(4,'February',2004))
print(date(9,'June',1949))

July 15, 2006
February 4, 2004
June 9, 1949


### 6 of 7 · The Return Statement

Pasemos la declaración `return`. Si miras la funcion `square()` función a continuación, pueded ver que devolvimos `squared_number`

In [58]:
def square(a_number):
    squared_number = a_number * a_number
    return squared_number

print(square(6))

36


In [59]:
def square(nmb):
    return nmb * nmb

squared_6 = square(6)
squared_11 = square(11)

print(squared_6, squared_11)

36 121


### 1 of 8 · Extraer valores de cualquier columna

En esta lección, aprenderemos cómo aprovechar el poder de las funciones para automatizar tareas repetitivas. Específicamente, crearemos una función que puede extraer datos de cualquier columna en un conjunto de datos representado como una lista de listas. **Este es un primer paso crucial en la generación de tablas de frecuencia, que son invaluables para el análisis de datos**.

En Python, las funciones sirven como bloques de código reutilizables que se pueden ejecutar varias veces con entradas variables. Esto mejora la eficiencia y legibilidad del código. Cuando se trata de grandes conjuntos de datos, las funciones nos permiten automatizar tareas rutinarias como la extracción de datos y el cálculo de frecuencia.

Nuestro conjunto de datos es una colección de información de la aplicación iOS organizada en una lista de listas. Cada sublista representa una fila, y cada elemento dentro de esa sublista corresponde a una columna. Por ejemplo, así es como podría verse una fila:

In [60]:
['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1']

['284882215',
 'Facebook',
 '389879808',
 'USD',
 '0.0',
 '2974676',
 '212',
 '3.5',
 '3.5',
 '95.0',
 '4+',
 'Social Networking',
 '37',
 '1',
 '29',
 '1']

Para facilitar nuestro análisis de datos, necesitamos realizar dos operaciones clave:

- Extraiga los valores de la columna en una lista separada
- Genere una tabla de frecuencias para los elementos de esa lista

<br>

Crearemos funciones separadas para cada una de estas tareas para mantener la modularidad y mejorar la reutilización del código. En esta pantalla, nos centraremos en la función de extracción de datos.

Para extraer los valores de cualquier columna que queramos de nuestra `apps_data` conjunto de datos, debemos completar lo siguiente:

- Cree una lista vacía que almacene los valores extraídos de la columna deseada.
- Bucle a través de `apps_data`  (excluyendo la fila de encabezado), y para cada iteración, haga lo siguiente:
    - Almacene el valor de la columna que queremos en una variable.
    - Añada ese valor a la lista vacía que creamos fuera del bucle for.

<br>

Aquí hay un ejemplo que extrae valores de la columna `cont_ratings`:

In [61]:
content_ratings = []
for row in apps_data[1:]:
    content_rating = row[10]
    content_ratings.append(content_rating)

### Instrucciones

(El conjunto de datos de la aplicación iOS está disponible en la pestaña csv en el editor a la derecha.)

1. Escribe una función llamada `extract()` eso puede extraer cualquier columna que desee de la `apps_data` conjunto de datos.

- La función debe incluir el número de índice de una columna como entrada (nombra el parámetro como quieras)
Dentro de la definición de la función, complete lo siguiente:

2. Crea una lista vacía

- Bucle a través del apps_data conjunto de datos (excluyendo el encabezado).
- Extraiga solo el valor que desee utilizando el parámetro (que será un número de índice)
- Añada ese valor a la lista vacía
- Devuelva la lista que contiene los valores de la columna

3. Usa el `extract()` función para extraer los valores en el `prime_genre` columnelos y guárdelos en una variable llamada genres. El número de índice de esta columna es 11.

In [62]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

In [63]:
print(apps_data[0])

['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic']


In [64]:
def extract(inx):
    return data[inx]

void_list = []

for data in apps_data[1:]:
    void_list.append(extract(11))

genres = void_list
#print(genres)

### 2 of 8 · Creating Frequency Tables

En el ejercicio anterior, creamos el `extract()` función, que podemos usar para extraer los valores de cualquier columna que queramos de nuestro conjunto de datos `apps_data`. Recuerda que queremos crear dos funciones:

- Una función que extrae los valores para cualquier columna que queramos en una lista separada (ya creamos esta función — es la `extract()` función)

- Una función que genera una tabla de frecuencias para una lista


En el siguiente ejercicio, crearemos la segunda función. Para crear una tabla de frecuencias para los elementos de una lista, tenemos que hacer lo siguiente:

- Crea un diccionario vacío.
- Recorre esa lista y comprueba cada iteración donde existe la variable iteración como clave en el diccionario creado.
- Si existe, entonces incremente por 1 el valor del diccionario en esa clave
- Si no existe, cree un nuevo par clave-valor en el diccionario, donde la clave del diccionario es la variable de iteración y el valor del diccionario es 1

In [65]:
# CODE FROM THE PREVIOUS SCREEN
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

def extract(index):
    column = []    
    for row in apps_data[1:]:
        value = row[index]
        column.append(value)    
    return column

genres = extract(11)

def freq_table(lista):
    dict = {}
    for run in lista:
        if run in dict:
            dict[run] += 1
        else:
            dict[run] = 1
    return dict

genres_ft = freq_table(genres)

print(genres_ft)

{'Social Networking': 167, 'Photo & Video': 349, 'Games': 3862, 'Music': 138, 'Reference': 64, 'Health & Fitness': 180, 'Weather': 72, 'Utilities': 248, 'Travel': 81, 'Shopping': 122, 'News': 75, 'Navigation': 46, 'Lifestyle': 144, 'Entertainment': 535, 'Food & Drink': 63, 'Sports': 114, 'Book': 112, 'Finance': 104, 'Education': 453, 'Productivity': 178, 'Business': 57, 'Catalogs': 10, 'Medical': 23}


### 3 of 8 · Writing a Single Function

En el ejercicio anterior, utilizamos dos funciones para crear nuestra tabla de frecuencias:

El `extract()` función, que extrae los valores de cualquier columna que queramos en una lista separada.
El `freq_table()` función, que genera una tabla de frecuencias para una lista.

Así que todo el proceso se compone de dos pasos clave:

Extraiga la columna que queremos como lista
Genere una tabla de frecuencias para esa lista
Sin embargo, podemos generar tablas de frecuencia sin extraer las columnas como un paso separado. Por ejemplo, así es como generamos la tabla de frecuencias para la columna de clasificaciones de contenido:


In [66]:
content_ratings = {}

for row in apps_data[1:]:
    c_rating = row[10] # we extract the values we want here
    if c_rating in content_ratings:
        content_ratings[c_rating] += 1
    else:
        content_ratings[c_rating] = 1

Esto significa que podemos escribir una sola función para generar las tablas de frecuencias para cualquier columna que queramos. Intentemos eso en el siguiente ejercicio.

### Instrucciones

Escribe una función llamada `freq_table()` eso genera una tabla de frecuencia para cualquier columna en nuestro conjunto de datos de aplicaciones de iOS.

La función debe tomar el número de índice de una columna como una entrada (nombre el parámetro como desee).
Dentro del cuerpo de la función, complete lo siguiente:

- Bucle a través del conjunto de datos `apps_data`(no incluya la fila de encabezado) y extraiga el valor que desee utilizando el parámetro (que será un número de índice).
  
- Construya la tabla de frecuencias como un diccionario.
- La función debe devolver la tabla de frecuencias como un diccionario.
- Usa la función `freq_table()` para generar una tabla de frecuencias para el `user_rating` columna (el número de índice de esta columna es 7). 

Almacene la tabla en una variable llamada `ratings_ft`.

In [67]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

def freq_table(index):
    frequency_table = {}
    
    for row in apps_data[1:]:
        value = row[index]
        if value in frequency_table:
            frequency_table[value] += 1
        else:
            frequency_table[value] = 1
            
    return frequency_table

ratings_ft = freq_table(7)

print(ratings_ft)

{'3.5': 702, '4.5': 2663, '4.0': 1626, '3.0': 383, '5.0': 492, '2.5': 196, '2.0': 106, '1.5': 56, '1.0': 44, '0.0': 929}


### 4 of 8 · Reusability and Multiple Parameters

En el ejercicio anterior, reafirmamos directamente sobre el conjunto de datos `apps_data`  dentro de la definición de la función:

In [68]:
def freq_table(index):
    frequency_table = {}

    for row in apps_data[1:]: # iterating over apps_data
        value = row[index]
        if value in frequency_table:
            frequency_table[value] += 1
        else:
            frequency_table[value] = 1
    return frequency_table

### Instrucciones
Actualizar la corriente `freq_table()` función para facilitar la reutilización.

La función debe incluir dos entradas esta vez: un conjunto de datos y el índice de una columna (nombre los parámetros que desee)
Dentro del cuerpo de la función, haga lo siguiente:
Recorre el conjunto de datos utilizando ese parámetro, que será un conjunto de datos (una lista de listas). Para cada iteración, seleccione el valor que desee utilizando el parámetro, que será un número de índice.
Construya la tabla de frecuencias como un diccionario.
La función debe devolver la tabla de frecuencias como un diccionario.
Utilice la actualización `freq_table()` función para generar una tabla de frecuencias para el `user_rating` columna (el número de índice de esta columna es 7). Almacene la tabla en una variable llamada `ratings_ft`.m

In [69]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

# INITIAL FUNCTION
def freq_table(data_set, index):
    frequency_table = {}
    
    for row in data_set[1:]:
        value = row[index]
        if value in frequency_table:
            frequency_table[value] += 1
        else:
            frequency_table[value] = 1
            
    return frequency_table

ratings_ft = freq_table(apps_data, 7)

### 5 of 8 · Keyword and Positional Arguments

Cuando una función tiene múltiples parámetros, hay más de una forma de pasar argumentos. 

Por ejemplo, si una función llamada `resta(a, b)`, toma `a` y `b` como entrada y devuelve el resultado de la resta `a - b`.

Cuando usamos la sintaxis `subtract(a=10, b=7)` o `subtract(b=7, a=10)`, pasamos en los argumentos `10` y `7` usando la variable nombres `a` y `b`. 

Por esta razón, los llamamos **argumentos de palabras clave**. Cuando usamos argumentos de palabras clave, el orden que usamos para pasar los argumentos no hace ninguna diferencia.  En nuestro ejemplo, Python sabe que el argumento `10` corresponde al parámetro `a`y el argumento `7` al parámetro `b`, independientemente de si usamos `subtract(a=10, b=7)` o `subtract(b=7, a=10)`

Esto se debe a que cuando especificamos  `a=10` y `b=7`, tenemos claro qué argumentos corresponden a qué parámetros y el orden que usamos para hacer estas especificaciones ya no importa.

Sin embargo, cuando usamos `subtract(10, 7)` o `subtract(7, 10)`, no tenemos claro qué argumentos corresponden a qué parámetros. Python mapea argumentos con parámetros por posición; el primer argumento se asignará al primer parámetro, y el segundo argumento se asignará al segundo parámetro.

Los argumentos posicionales a menudo son ventajosos porque implican menos escritura y pueden acelerar nuestro flujo de trabajo. Sin embargo, debemos prestar especial atención al orden que utilizamos para evitar asignaciones incorrectas que pueden conducir a errores lógicos.

In [70]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

print(apps_data[0])

['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic']


In [71]:
def freq_table(data_set, index):
    frequency_table = {}
    
    for row in data_set[1:]:
        value = row[index]
        if value in frequency_table:
            frequency_table[value] += 1
        else:
            frequency_table[value] = 1
        
    return frequency_table

content_ratings_ft = freq_table(apps_data, 10)
ratings_ft = freq_table(data_set=apps_data, index=7)
genres_ft = freq_table(index=11, data_set=apps_data)

print(content_ratings_ft)
print(ratings_ft)
print(genres_ft)

{'4+': 4433, '12+': 1155, '9+': 987, '17+': 622}
{'3.5': 702, '4.5': 2663, '4.0': 1626, '3.0': 383, '5.0': 492, '2.5': 196, '2.0': 106, '1.5': 56, '1.0': 44, '0.0': 929}
{'Social Networking': 167, 'Photo & Video': 349, 'Games': 3862, 'Music': 138, 'Reference': 64, 'Health & Fitness': 180, 'Weather': 72, 'Utilities': 248, 'Travel': 81, 'Shopping': 122, 'News': 75, 'Navigation': 46, 'Lifestyle': 144, 'Entertainment': 535, 'Food & Drink': 63, 'Sports': 114, 'Book': 112, 'Finance': 104, 'Education': 453, 'Productivity': 178, 'Business': 57, 'Catalogs': 10, 'Medical': 23}


### 6 of 8 · Combining Functions

Reutilización de funciones.

In [72]:
def find_sum(a_list):
    a_sum = 0
    for element in a_list:
        a_sum += float(element)
    return a_sum

def find_length(a_list):
    length = 0
    for element in a_list:
        length += 1
    return length

si uno quiere hacer la media, entonces debería en primer lugar encontrar la suma y despues la cantidad de elementos sumados.

In [73]:
def mean(a_list_of_numbers):
    sum_list = find_sum(a_list_of_numbers)
    len_list = find_length(a_list_of_numbers)
    mean_list = sum_list / len_list

    return mean_list

list_1 = [10, 5, 15]
print(mean(list_1))

10.0


Se puede ver que dentro de la función `mean()` se ha reutilizado las funciones anteriores. Esto es importante porque ahorra tiempo y permite elaborar funciones dentro de otras funciones, abstrayendonos de las funciones por definición.

### Instructions

1. Write a function named `mean()` that computes the mean for any column we want from a dataset.

- The function should take in two inputs: a dataset and an index value.
- Inside the body of the `mean()` function, use the `extract()` function to extract the values of a column into a separate list, and then compute the mean of the values in that list using `find_sum()` and `find_length()`.
- The function should return the mean of the column.

2. Use the mean() function to compute the mean of the price column (index number 4) and assign the result to a variable named avg_price.

In [74]:
opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

def extract(data_set, index):
    column = []    
    for row in data_set[1:]:
        value = row[index]
        column.append(value)    
    return column

def find_sum(a_list):
    a_sum = 0
    for element in a_list:
        a_sum += float(element)
    return a_sum

def find_length(a_list):
    length = 0
    for element in a_list:
        length += 1
    return length


def mean(data_set, index):
    sum = 0
    length = 0
    list = []
    list = extract(data_set, index)
    sum = find_sum(list)
    length = find_length(list)
    return sum / length

avg_price = mean(apps_data, 4)
print(avg_price)

1.7262178685562666


### Python Functions: Arguments, Parameters, and Debugging
7 of 8 · Debugging Functions



In [75]:

avg_price = None
avg_rating = None

opened_file = open('AppleStore.csv')
from csv import reader
read_file = reader(opened_file)
apps_data = list(read_file)

def extract(data_set, index):
    column = []
    
    for row in data_set[1:]:
        value = float(row[index])
        column.append(value)
    
    return column

def find_sum(a_list):
    a_sum = 0
    for element in a_list:
        a_sum += element
    return a_sum

def find_length(a_list):
    length = 0
    for element in a_list:
        length += 1
    return length

def mean(data_set, index):
    column = extract(data_set, index)
    return find_sum(column) / find_length(column)

avg_price = mean(apps_data, 4)
avg_rating = mean(apps_data, 7)

print(avg_price)
print(avg_rating)

1.7262178685562666
3.526955675976101


### 1 of 7 · Interfering with the Built-In Functions

En esta lección, vamos a explorar algunas herramientas útiles en Python: funciones integradas y cómo usarlas de manera efectiva, estableciendo valores predeterminados para argumentos de funciones y cómo usar más de una instrucción de retorno en una función. Además, aprenderemos cómo encontrar información útil en la documentación oficial de Python.

No se recomienda nombrar nuestras funciones igual que las funciones integradas. Puede causar problemas inesperados en nuestro código y dificultar que otros entiendan lo que está sucediendo.

### 2 de 7 ''Nombres Variables y Funciones Incorporadas

[Built-in Functions](https://docs.python.org/3/library/functions.html)

### 3 de 7 ''Argumentos Predeterminados

Cuando creamos una función, podemos iniciar parámetros con ciertos valores predeterminados — que llamamos estos **valores argumentos predeterminados**.

In [76]:
def add_value(x, constant=10):
    return x + constant

print(add_value(3))

13


Los argumentos predeterminados son fáciles de modificar cuando llamamos a una función:

In [77]:
def add_value(x, constant=10):
    return x + constant

print(add_value(3, constant=50))
print(add_value(3, constant=26))
print(add_value(3, constant=97))

53
29
100


Si todos los parámetros tienen argumentos predeterminados, entonces podemos llamar a una función sin pasar un argumento:

In [78]:
def add_value(x=9, constant=10):
    return x + constant

print(add_value())

19


Los argumentos predeterminados son útiles cuando anticipamos que usaremos un argumento con frecuencia.

Ahora construyamos una función que abra un archivo CSV y haga uso de argumentos predeterminados al mismo tiempo. Hemos creado una función llamada open_dataset() eso toma el nombre de un archivo CSV como entrada y devuelve el archivo como una lista de listas.

### Instrucciones

Editar la función `open_dataset()` y agregue el nombre del conjunto de datos de aplicaciones de iOS ('AppleStore.csv') como argumento predeterminado para el parámetro `file_name`.

Sin pasar ningún argumento, use la función open_dataset() para abrir el archivo `AppleStore.csv`. 

Asigne el conjunto de datos a una variable llamada `apps_data`.

Inspeccionar el conjunto `apps_data` conjunto de datos después de ejecutar el código para confirmar que todo salió como se esperaba. Puede intentar imprimir las primeras filas o simplemente usar el inspector de variables del editor de código.

In [79]:
def open_dataset(file_name):
    opened_file = open(file_name)
    from csv import reader
    read_file = reader(opened_file)
    data = list(read_file)
    
    return data

apps_data = open_dataset('AppleStore.csv')

print(apps_data[0:2])

[['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic'], ['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1']]


### 5 of 7 · Multiple Return Statements

Digamos que queremos escribir una sola función que tome dos números como entrada y sea lo suficientemente flexible como para volver o la suma de los dos números o la diferencia entre los dos números (restando un número de otro).

Tal vez sería más fácil escribir dos funciones diferentes — una para calcular la suma y otra para calcular la diferencia — pero nuestro objetivo es escribir una sola función. Para construir esta función, necesitamos especificar si queremos la suma o la diferencia. Parece, sin embargo, que debemos elegir la suma o la diferencia en nuestro return declaración.

Afortunadamente, es posible hacer uso de múltiples declaraciones de return. 
Combinando return con un if  y un else, podemos especificar si queremos una suma o una diferencia devuelta:

In [80]:
def sum_or_difference(a, b, return_sum=True):
    if return_sum:
        return a + b
    else:
        return a - b

print(sum_or_difference(10, 5, return_sum=True))
print(sum_or_difference(10, 5, return_sum=False))

15
5


### 6 de 7 ''No usar `else`

El enfoque anterior funciona porque una función deja de ejecutar su código de definición tan pronto como un return la declaración se ejecuta. Si hay algún código restante después de eso return declaración, no se ejecutará.

In [81]:
def sum_or_difference(a, b, return_sum=True):
    if return_sum:
        return a + b

    return a - b

print(sum_or_difference(10, 5, return_sum=True))
print(sum_or_difference(10, 5, return_sum=False))

15
5


### Instrucciones

Modificar el `open_dataset()` función para que no use un else cláusula para devolver el conjunto de datos tal como está si el parámetro indica que no hay fila de encabezado.

Utilice la actualización open_dataset() función para abrir el AppleStore.csv archivo — recuerda que el AppleStore.csv el conjunto de datos tiene una fila de encabezado. Asigne el conjunto de datos a una variable denominada apps_data.

In [82]:
file_open = open('AppleStore.csv')

from csv import reader
open_reader = reader(file_open)

dataset = list(open_reader)
print(dataset[0:1])

[['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic']]


In [83]:
def open_dataset(file_name='AppleStore.csv', header=True):        
    opened_file = open(file_name)
    from csv import reader
    read_file = reader(opened_file)
    data = list(read_file)
    
    if header:
        return data[0:2]
    return data[1:2]


open_dataset(file_name='AppleStore.csv', header=True) 

[['id',
  'track_name',
  'size_bytes',
  'currency',
  'price',
  'rating_count_tot',
  'rating_count_ver',
  'user_rating',
  'user_rating_ver',
  'ver',
  'cont_rating',
  'prime_genre',
  'sup_devices.num',
  'ipadSc_urls.num',
  'lang.num',
  'vpp_lic'],
 ['284882215',
  'Facebook',
  '389879808',
  'USD',
  '0.0',
  '2974676',
  '212',
  '3.5',
  '3.5',
  '95.0',
  '4+',
  'Social Networking',
  '37',
  '1',
  '29',
  '1']]

In [84]:
open_dataset(file_name='AppleStore.csv', header=False) 

[['284882215',
  'Facebook',
  '389879808',
  'USD',
  '0.0',
  '2974676',
  '212',
  '3.5',
  '3.5',
  '95.0',
  '4+',
  'Social Networking',
  '37',
  '1',
  '29',
  '1']]

### Python Functions: Returning Multiple Variables and Function Scopes
1 of 8 · Returning Multiple Variables

En esta lección, repasaremos funciones que devuelven múltiples variables, objetos y tuplas mutables e inmutables, comportamiento de funciones y ámbitos de funciones. 

Anteriormente, escribimos una función que podía devolver una suma o una diferencia. Pero, ¿qué pasa si queremos escribir una función que devuelva una suma y una diferencia al mismo tiempo?

Afortunadamente, Python nos permite construir funciones que devuelven más de una variable. Esto significa que podemos crear una función que devuelva una suma y una diferencia.



In [85]:
def sum_and_difference (a, b):
    a_sum = a + b
    difference = a - b
    return a_sum, difference
    # Separate variable names with a comma

sum_diff = sum_and_difference(15, 5)
print(sum_diff)

(20, 10)


(20, 10) es una **tupla**, que es un tipo de datos que es muy similar a una lista (ejemplos de tipos de datos incluyen enteros, cadenas, listas, diccionarios, etc.). Aprenderemos sobre tuplas a continuación. 

### 2 of 8 · Tuples

Una tupla es una estructura de datos en Python que es bastante similar a una lista pero con algunas diferencias clave. Una forma común de encontrar una tupla es cuando una función devuelve múltiples valores.

Al igual que una lista, generalmente usamos una tupla para almacenar múltiples valores. Para crear una tupla, usamos paréntesis para encerrar los elementos, separados por comas. Así es como creamos y verificamos el tipo de tupla:

In [86]:
a_list = [1, 'a', 10.5]
a_tuple = (1, 'a', 10.5)

print(a_tuple)
print(type(a_tuple))

(1, 'a', 10.5)
<class 'tuple'>


Las tuplas admiten indexación positiva y negativa, al igual que las listas

Las tuplas son inmutables, lo que significa que sus elementos no pueden ser alterados una vez creados

En contraste, las listas son mutables

### Instrucciones

Editar la función `open_dataset()` función (ya está en el editor de código) para hacer lo siguiente:

Si el conjunto de datos tiene un encabezado, la función devuelve por separado el encabezado y el resto del conjunto de datos.
Si no hay encabezado, la función devuelve todo el conjunto de datos.
Utilice la actualización `open_dataset()` función para abrir el AppleStore.csv archivo, que tiene una fila de encabezado.

Asigne el resultado la variable `all_data`.
Utilice la indexación de tupla para extraer el encabezado y el resto del conjunto de datos del `all_data` tupla.
Asigne el encabezado a una variable nombrada `header`.
Asigne el resto del conjunto de datos a una variable nombrada `apps_data`.

In [87]:
def open_dataset(file_name='AppleStore.csv', header=True):        
    opened_file = open(file_name)
    from csv import reader
    read_file = reader(opened_file)
    data = list(read_file)
    
    if header:
        return data[0], data[1:3]
    else:
        return data[-2:-1]

all_data = open_dataset()
header = all_data[0]
apps_data = all_data[1]

print(str(all_data) + "\n" + "\n" + str(header) + "\n" + "\n" + str(apps_data))

(['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic'], [['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1'], ['389801252', 'Instagram', '113954816', 'USD', '0.0', '2161558', '1289', '4.5', '4.0', '10.23', '12+', 'Photo & Video', '37', '0', '29', '1']])

['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic']

[['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1'], ['389801252', 'Instagram', '113954816', 'USD', '0.0', '2161558', '1289', '4.5', '4.0', '10.23', '12+', 'Phot

### 3 of 8 · More About Tuples

Las tuplas en Python tienen algunas características convenientes, lo que aumenta su versatilidad. Cuando creamos una tupla, rodear los valores con paréntesis es opcional. Es suficiente escribir los valores individuales y separar cada uno con una coma. 

In [88]:
a_tuple = (1, 'a')
print(a_tuple)
print(type(a_tuple))

(1, 'a')
<class 'tuple'>


In [89]:
a_tuple = 1, 'a'
print(a_tuple)
print(type(a_tuple))

(1, 'a')
<class 'tuple'>


Con esto en mente, recuerde la sintaxis que usamos en el return declaración para devolver múltiples valores:

In [90]:
def sum_and_difference (a, b):
    a_sum = a + b
    difference = a - b
    return a_sum, difference
    # Separate variable names with a comma

sum_diff = sum_and_difference(15, 5)
print(sum_diff)

(20, 10)


Python en la salida de la función cree que múltiples variables se devuelven como tuplas.

Pero si queremos devolver una lista en lugar de una tupla, necesitamos usar corchetes:



In [91]:
def sum_and_difference (a, b):
    a_sum = a + b
    difference = a - b
    return [a_sum, difference]
    # Use brackets to return a list

sum_diff = sum_and_difference(15, 5)
print(sum_diff)
print(type(sum_diff))

[20, 10]
<class 'list'>


In [92]:
def open_dataset(file_name='AppleStore.csv', header=True):        
    opened_file = open(file_name)
    from csv import reader
    read_file = reader(opened_file)
    data = list(read_file)
    
    if header:
        return data[0], data[1:]
    else:
        return data[-2:-1]
    
header, apps_data = open_dataset()

### 4 of 8 · No Return Statement


Hasta ahora, hemos estado usando parámetros y return declaraciones para todas nuestras funciones. Sin embargo, los parámetros y return las declaraciones son opcionales

Funciones sin a return la declaración no devuelve ningún valor. Estrictamente hablando, devuelven un None valor que representa la ausencia de un valor.

In [93]:
def price(item, cost):
    print("The " + item + " costs $" + str(cost) + ".")

print(price("chair", 40.99))
print(price("book", 12.84))
print(price("soap", 3.95))

The chair costs $40.99.
None
The book costs $12.84.
None
The soap costs $3.95.
None


### 5 of 8 · Function Behavior

Recordemos que Python no ejecuta el código que escribimos dentro de la definición de una función hasta que llamamos a esa función.

In [94]:
def print_constant():
    xx = 3.14
    print(xx)

print(xx)

NameError: name 'xx' is not defined

In [95]:
print_constant()

3.14


### 6 de 8 ''Alcances — Global y Local

Cuando llamamos print_constant(), x = 3.14 ejecuta, pero la peculiaridad es que Python solo guarda el x variable temporalmente.

La memoria temporal asociada con una función es aislado de la memoria asociada al programa principal. Como resultado, podemos inicializar una variable x = 10 en el programa principal, y luego ejecutar x = 3.14 en el cuerpo de una función sin sobrescribir el x variable del programa principal.

In [96]:
x = 10

def print_constant():
    x = 3.14
    print(x)

print_constant()
print(x)

3.14
10


Este aislamiento de memoria es útil porque no tenemos que preocuparnos por sobrescribir variables del programa principal cuando escribimos funciones — o viceversa. Esto es especialmente útil cuando se hace difícil recordar todos los nombres de variables utilizados al escribir programas grandes.

Este aislamiento de memoria también significa que algunas variables se pueden acceder sólo desde ciertas partes de un programa. Ya hemos visto en uno de los ejemplos anteriores que no pudimos acceder x del programa principal, porque solo se definió en la definición de función que está aislada de memoria del programa principal.

In [97]:
def print_constant():
    xy = 3.14
    print(xy)

print_constant()
print(xy)

3.14


NameError: name 'xy' is not defined

### Instrucciones

Crear una función llamada `exponential()` eso toma un solo parámetro nombrado x.

Dentro de la definición de la función, complete lo siguiente:
Asignar 2.72 a una variable nombrada `e`.
Imprimir `e`.
La función debe regresar `e` a la potencia de `x`.
Llama al `exponential()` función con un argumento de 5. Asigne el resultado a una variable nombrada `result`.
Hipótesis de lo que debe ver si imprimió e en el programa principal después de llamar al `exponential()` función. Imprimir e para confirmar o negar su hipótesis.
Crea una nueva función llamada `divide()`, que no toma ningún parámetro, y luego llama a la función.

Dentro de la definición de la función, complete lo siguiente:
Imprimir el `a_sum variable`.
Imprimir el `length variable`.
La función debe devolver el resultado de la división entre `a_sum` y `length`.
Llama al `divide()` función e intente asignar el resultado a una variable nombrad¡ `result_2`. Antes de ejecutar el código, hipotetice si obtendremos un error o no.

In [98]:
e = 'mathematical constant'
a_sum = 1000
length = 50


def exponential(x):
    e = 2.72
    print(e)
    return e**x

result = exponential(5)
print(e)

def divide():
    print(a_sum)
    print(length)
    return a_sum / length

result_2 = divide()
print(result_2)

2.72
mathematical constant
1000
50
20.0
